#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2002 University of Utah and the Flux Group.
# All rights reserved.
#

#
# Boottime initialization. 
#
case "$1" in
start)
	/usr/local/etc/emulab/watchdog > /dev/null 2>&1 && echo -n ' Emulab'

	#
	# Do not start the mini server on RON nodes yet. 
	#
	if [ -x /usr/local/etc/emulab/webserver.pl -a -e /etc/emulab.pkey ]
	then
		/usr/local/etc/emulab/webserver.pl && echo -n ' Webserver'
	fi
	;;
stop)
	if [ -f /var/run/emulab-watchdog.pid ]; then
	    kill `cat /var/run/emulab-watchdog.pid` && echo -n ' Emulab'
	fi
	if [ -f /var/run/webserver.pid ]; then
	    kill `cat /var/run/webserver.pid` && echo -n ' Webserver'
	fi
	;;
*)
	echo "Usage: `basename $0` {start|stop}" >&2
	;;
esac

exit 0
