#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2004 University of Utah and the Flux Group.
# All rights reserved.
#

. /etc/emulab/paths.sh

if [ -r $BOOTDIR/controlif ]; then
    cat $BOOTDIR/controlif
else
    echo 'unknown'
fi
