#!/bin/bash
#
# EMULAB-COPYRIGHT
# Copyright (c) 2006, 2007 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

#
# testbed       Run "prepare" on the way down.
#
# description:	Clean up node using Emulab's prepare script.

# Source networking configuration.
if [ -f /etc/sysconfig/network ]; then
    . /etc/sysconfig/network
elif [ -f /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions
fi

RETVAL=0

# Oh, give me a break! Linux rc greps for keywords "daemon |action " to
# determine if stdout/stderr should be redirected! So, put this stupid
# line here so that output goes to the console!
#
# daemon action 

# See how we were called.
case "$1" in
  start)
	# We do not do anything; this is strictly for reboot time.
	# Note: /var/lock/subsys/tbprepare will be created later, as needed.
	;;
  stop)
        #
        # Note the Ubuntu does not use the /var/lock/subsys files
        # so we will get here on every shutdown, not just when the
        # subsys file exists.
        #
        if [ -f /var/lock/subsys/tbprepare ]; then
  	    rm -f /var/lock/subsys/tbprepare
	    echo "Running Testbed prepare script ..."
	    $BINDIR/prepare 2>&1 | tee /prepare.log
	    $BINDIR/logboot /prepare.log
	    rm -f /prepare.log
	    echo "Informing the testbed we're rebooting ..."
	    $BINDIR/tmcc state SHUTDOWN
	    RETVAL=$?
	fi
	;;
  status)
	echo "Peachy"
	;;
  restart)
	echo "Done"
	;;
  reload)
	echo "Done"
	;;
  *)
	echo "Usage: testbed {start|stop|restart|reload|status}"
	exit 1
esac

exit $RETVAL
