EXECUTABLE=UdpClient
CC=g++ -g
CFLAGS=

COMPILE_DIR=.OBJECTS

OBJECTS=${COMPILE_DIR}/UdpClient.o \
	${COMPILE_DIR}/UdpPacketSensor.o \
	${COMPILE_DIR}/UdpMinDelaySensor.o \
	${COMPILE_DIR}/UdpMaxDelaySensor.o \
	${COMPILE_DIR}/UdpThroughputSensor.o \
	${COMPILE_DIR}/UdpPacketInfo.o \
	${COMPILE_DIR}/UdpSensor.o


COMMON_INCLUDES=UdpLibs.h \
		UdpState.h

${EXECUTABLE}: ${OBJECTS} 
	${CC} -o $@ ${CFLAGS} $+ -lpcap

${COMPILE_DIR}/UdpClient.o: UdpClient.cc UdpPacketSensor.h ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpMinDelaySensor.o: UdpMinDelaySensor.cc UdpMinDelaySensor.h  ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpMaxDelaySensor.o: UdpMaxDelaySensor.cc UdpMaxDelaySensor.h  ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpThroughputSensor.o: UdpThroughputSensor.cc UdpThroughputSensor.h  ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpPacketSensor.o: UdpPacketSensor.cc UdpPacketSensor.h  ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpPacketInfo.o: UdpPacketInfo.cc UdpPacketInfo.h  ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

${COMPILE_DIR}/UdpSensor.o: UdpSensor.cc UdpSensor.h ${COMMON_INCLUDES}
	${CC} -c ${CFLAGS} -o $@ $<

clean:
	rm -f ${COMPILE_DIR}/*.o ${EXECUTABLE}

