#!/usr/bin/perl -w
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2003 University of Utah and the Flux Group.
# All rights reserved.
#
use English;

#
# Send a Testbed Control event.
#
# usage: sendevent <event>
# 

# Drag in path stuff so we can find emulab stuff.
BEGIN { require "/etc/emulab/paths.pm"; import emulabpaths; }

#
# We use the tmcc to figure out where the Testbed Event Daemon is running.
# Don't worry about the port for now.
#
use libtmcc;

unshift(@ARGV, ("-s", tmccbossname()));

exec "tevc", @ARGV;

die("Could not exec tbevc: $!");
