#! /bin/sh                                                                      
                                                                                
create_home=0                                                                   
                                                                                
cmdline=""                                                                      
for arg in "$@"; do                                                             
	case "$arg" in                                                          
		-m) create_home=1 ;;                                            
		*) cmdline="$cmdline '$arg'" ;;                                 
	esac                                                                    
done                                                                            
                                                                                
if [ $create_home -ne 1 ]; then                                                 
	cmdline="$cmdline -H"                                                   
fi                                                                              
                                                                                
eval exec adduser $cmdline
