#!/bin/sh

TRANGCMD="java -jar ${TRANG:-/usr/local/share/java/classes/trang.jar}"

### TEMPORARY! Remove when version 0.2 is checked in ###
rm -f *.xsd

for schema in rspec-ad rspec-request; do
  $TRANGCMD ${schema}.rnc ${schema}.xsd

  mv top.xsd ${schema}-top.xsd
  sed "s/top.xsd/${schema}-top.xsd/" protogeni-rspec-common.xsd > ${schema}-common.xsd
  rm protogeni-rspec-common.xsd
  sed "s/protogeni-rspec-common.xsd/${schema}-common.xsd/" ${schema}.xsd > ${schema}.tmp
  mv ${schema}.tmp ${schema}.xsd
done
### END TEMPORARY

for path in 0.1; do
  rm -f ${path}/*.xsd
  for schema in ad request; do
    $TRANGCMD ${path}/${schema}.rnc ${path}/${schema}.xsd

    mv ${path}/top.xsd ${path}/${schema}-top.xsd
    sed "s/top.xsd/${schema}-top.xsd/" ${path}/common.xsd > ${path}/${schema}-common.xsd
    rm ${path}/common.xsd
    sed "s/common.xsd/${schema}-common.xsd/" ${path}/${schema}.xsd > ${path}/${schema}.tmp
    mv ${path}/${schema}.tmp ${path}/${schema}.xsd
  done
done
