#!/bin/sh

TRANGCMD="java -jar ${TRANG:-/usr/local/share/java/classes/trang.jar}"

for path in 0.1 0.2 2; do
  rm -f ${path}/{ad-common,ad,any-extension,manifest-common,manifest-request,manifest,request-common,request,ad-top,manifest-top,request-top}.xsd

  ### Manifest
  $TRANGCMD ${path}/manifest.rnc ${path}/manifest.xsd
  if [ ${path} = 0.1 ] || [ ${path} = 0.2 ]; then
    mv ${path}/top.xsd ${path}/manifest-top.xsd
    sed "s/top.xsd/manifest-top.xsd/" ${path}/common.xsd > ${path}/manifest-common.xsd
  else
    sed "s/any-extension.xsd/any-extension-schema.xsd/" ${path}/common.xsd > ${path}/manifest-common.xsd
  fi
  rm ${path}/common.xsd
  sed "s/common.xsd/manifest-common.xsd/" ${path}/request.xsd > ${path}/manifest-request.xsd
  rm ${path}/request.xsd
  sed "s/request.xsd/manifest-request.xsd/" ${path}/manifest.xsd > ${path}/manifest.tmp
  mv ${path}/manifest.tmp ${path}/manifest.xsd
  ### End Manifest

  for schema in ad request; do
    $TRANGCMD ${path}/${schema}.rnc ${path}/${schema}.xsd

    if [ ${path} = 0.1 ] || [ ${path} = 0.2 ]; then
      mv ${path}/top.xsd ${path}/${schema}-top.xsd
      sed "s/top.xsd/${schema}-top.xsd/" ${path}/common.xsd > ${path}/${schema}-common.xsd
    else
      sed "s/any-extension.xsd/any-extension-schema.xsd/" ${path}/common.xsd > ${path}/${schema}-common.xsd      
    fi
    rm ${path}/common.xsd
    sed "s/common.xsd/${schema}-common.xsd/" ${path}/${schema}.xsd > ${path}/${schema}.tmp
    if [ ${path} = 0.1 ] || [ ${path} = 0.2 ]; then
      mv ${path}/${schema}.tmp ${path}/${schema}.xsd
    else
      sed "s/any-extension.xsd/any-extension-schema.xsd/" ${path}/${schema}.tmp > ${path}/${schema}.xsd
      rm ${path}/${schema}.tmp
    fi
  done

  sudo scp ${path}/*.xsd ${path}/*.rnc ops.emulab.net:/usr/local/www.geni/data/trac/resources/rspec/${path}/
done

for path in ext/gre-tunnel/1; do
  for schema in ad request manifest; do
    if [ -e ${path}/${schema}.rnc ]; then
      $TRANGCMD ${path}/${schema}.rnc ${path}/${schema}.xsd
      sudo scp ${path}/${schema}.xsd ${path}/${schema}.rnc ops.emulab.net:/usr/local/www.geni/data/trac/resources/rspec/${path}/
    fi
  done
done

# Compile extensions
for path in ext/emulab/1/; do
    for schema in top_extension ptop_extension vtop_extension; do 
	if [ -e ${path}/${schema}.rnc ]; then
	    $TRANGCMD ${path}/${schema}.rnc ${path}/${schema}.xsd 
	    sudo scp ${path}/${schema}.xsd ${path}/${schema}.rnc ops.emulab.net:/usr/local/www.geni/data/trac/resources/rspec/${path}/
	fi
    done
done

cd ../security

for path in ext/policy/1; do
  if [ -e ${path}/policy.rnc ]; then
    $TRANGCMD ${path}/policy.rnc ${path}/policy.xsd
    sudo scp ${path}/policy.xsd ${path}/policy.rnc ops.emulab.net:/usr/local/www.geni/data/trac/resources/credential/${path}/
  fi
done

