#! /bin/sh

if [ -n "$PHYSDEVPATH" ]; then
	device=/sys/$PHYSDEVPATH
else
	device=/sys/$DEVPATH
fi

[ -L $device/driver ] && exit 0
[ -f $device/modalias ] || exit 0

modprobe `cat $device/modalias` 2> /dev/null
