#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2002 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

#
# Jail startup. To be run inside of a jail!
#
case "$1" in
start)
        $BINDIR/jaildog.pl > /dev/null 2>&1
	echo -n ' Emulab'
	;;
stop)
	#
	# Don't bother. Inside of a jail everything gets killed at once.
	#
	echo -n ' Emulab'
	;;
*)
	echo "Usage: `basename $0` {start|stop}" >&2
	;;
esac

exit 0
