#!/bin/sh
if [ ! -d ns-allinone-2.26 ]; then
    echo "Downloading ns2.26 source from www.emulab.net"
    fetch http://www.emulab.net/ns-allinone-2.26.tar.gz
    if [ $? -ne 0 ]; then
        echo "Failed..."
        echo "Downloading ns2.26 source from www.isi.edu"
        fetch http://www.isi.edu/nsnam/dist/ns-allinone-2.26.tar.gz
    fi
    tar xzf ns-allinone-2.26.tar.gz
    patch -p0 < nse.patch
fi
cd ns-allinone-2.26
./install
cp ns-2.26/nse ..
