#!/usr/bin/perl -w
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2002 University of Utah and the Flux Group.
# All rights reserved.
#
use English;

#
# Setup the files and environment required for NSE and start it
#
# usage: startnse &
# 

# Drag in path stuff so we can find emulab stuff.
BEGIN { require "/etc/emulab/paths.pm"; import emulabpaths; }

# Stuff is here now.
chdir $BINDIR;

$id = `id`;
($vnode,$eid,$pid) = split (/\./, `hostname`);
$logpath = "/proj/$pid/exp/$eid/logs/nse-$vnode.log";
umask(002);
open( STDOUT, ">>$logpath");
open( STDERR, ">>&STDOUT" );
if( $id =~ /uid=(\d+)/ ) {
    if( $1 ne "0" ) {
        system("sudo nse nseinput.tcl");
    } else {
        system("nse nseinput.tcl");
    }
}
