#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2003 University of Utah and the Flux Group.
# All rights reserved.
#

. /etc/emulab/paths.sh

NODETYPE=`nodetype`
case $NODETYPE in
pc300|pc850)
    echo 'fxp0'
    ;;
pcL440GX)
    echo 'fxp1'
    ;;
pc600)
    echo 'fxp4'
    ;;
pc1500|pc2000)
    echo 'xl0'
    ;;
*)
    echo 'unknown';
    ;;
esac
