#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2002 University of Utah and the Flux Group.
# All rights reserved.
#

NODETYPE=`/etc/testbed/nodetype`

if [ "$NODETYPE" = 'pc600' ]; then
    echo 'fxp4'
elif [ "$NODETYPE" = 'pc850' ]; then
    echo 'fxp0'
elif [ "$NODETYPE" = 'pcL440GX' ]; then
    echo 'fxp1'
elif [ "$NODETYPE" = 'pc1500' ]; then
    echo 'xl0'
fi
