#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2003 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

#
# Remember our server IP, real hostname, router IP, etc.
#
if [ x$reason = xREBOOT ] || [ x$reason = xBOUND ] || [ x$reason = xRENEW ]
then
	echo $new_dhcp_server_identifier > $BOOTDIR/bossip
	echo $new_host_name > $BOOTDIR/realname
	echo $new_routers > $BOOTDIR/routerip
	echo $new_ip_address > $BOOTDIR/myip
fi

#
# See if the Testbed configuration software wants to change the hostname.
# Installed into /etc.
# 
$BINDIR/sethostname $new_domain_name

#
# Once we have an IP address, we can stop dhclient so that it doesn't get
# in the way 
#
if [ x$reason = xREBOOT ] || [ x$reason = xBOUND ] || [ x$reason = xRENEW ]
then
	# I'd love to use the dhclient.pid file, but it helpfully has not been
	# created at this point
	killall dhclient
fi  

exit 0
