#!/usr/bin/perl
use Modern::Perl;
use lib 'lib';
use TestBed::TestSuite::Experiment::Macros;
use Data::Dumper;
use Tools::TBSSH;

sub listexps {
  output(list_full)
}

my $ns = <<'NSEND';
source tb_compat.tcl

set ns [new Simulator]

set node1 [$ns node]
set node2 [$ns node]

set lan1 [$ns make-lan "$node1 $node2" 100Mb 0ms]
$ns run
NSEND

sub output {
  my ($h) = @_;
  while(my ($pk, $v) = each %$h) {
    while(my ($gk, $v) = each %$v) {
      for my $e (@$v) {
        my $eid;
        given ($e) {
          when('name') { $eid = sprintf("%s %s", $e->{'name'}, $e->{'state'});}
          default { $eid = $e; }
        };
          
        say "$pk :: $gk :: $eid";
      }
    }
  }
}
my $pid = 'tbres';
if (@ARGV) {
  $_ = $ARGV[0];
  my $eid = $ARGV[1];
  my $e = e($pid, $eid);
  if (/end/) { $e->end(); }
  elsif ( /ping/ ) {
    my $nodes = $e->nodeinfo();
    for (@$nodes) {
     say; 
     use Tools::PingTest;
     ping($_);
    }
  }
  elsif (/start/) { $e->batchexp_ns_wait($ns); }
}
else {
  listexps();
}

# vim: ft=perl:
