#!/usr/bin/perl
#add lib directory to library search path
use lib qw(lib tests);
use SemiModern::Perl;


#add localcpan path to library search path
if (-f glob("~/lib/perl5/Test/Harness.pm")) {
  my $localcpan_path = glob('~/lib/perl5');
  my $p5l = $ENV{PERL5LIB};
  unless ( (defined $p5l) && ($p5l =~ /$localcpan_path/)) {
    my $sep = (defined $p5l) ? ":" : "";
    $ENV { PERL5LIB} .= "$sep" . " $localcpan_path";
  }
}
#add tests directory to library search path
$ENV{PERL5LIB} .= ":tests";

use Data::Dumper;

{
  use Getopt::Long;
  my $pjobs   = 1;
  my $timing;
  my $verbose;

  my $logging = 0;
  my $debug;
  my $project;
  my $group;
  my $xmlrpcurl;

  my $cmdline_defines;
  my $concurrent_prerun_jobs;
  my $concurrent_node_usage;
  my $exclude_steps;
  my $single;
  my $result = GetOptions (
      "d|debug"     => \$debug,
      "define=s%"   => \$cmdline_defines,
      "jobs=i"      => \$pjobs,
      "logging=i"   => \$logging,
      "timing"      => \$timing,
      "verbose"     => \$verbose,
      "project=s"   => \$project,
      "xmlrpcurl=s" => \$xmlrpcurl,
      "group=s"     => \$group,
      "cprj=i"      => \$concurrent_prerun_jobs,
      "cnu=i"       => \$concurrent_node_usage,
      "exsteps=s"   => \$exclude_steps,
      "single=s"   => \$single,
    );

  if ($pjobs > 1) { $ENV { 'HARNESS_OPTIONS' } = "j$pjobs"; }
  if ($timing)    { $ENV { 'HARNESS_TIMER'   } = 1; }
  if ($verbose)   { $ENV { 'HARNESS_VERBOSE' } = 1; $ENV { 'HARNESS_COLOR' } = 1; }

  if ($debug)     { $ENV { 'TBTS_DEBUG'      } = 1          ; $TBConfig::DEBUG_XML_CLIENT = 1       ; }
  if ($group)     { $ENV { 'TBTS_GROUP'      } = $group     ; $TBConfig::DEFAULT_GID = $group       ; }
  if ($project)   { $ENV { 'TBTS_PROJECT'    } = $project   ; $TBConfig::DEFAULT_PID = $project     ; }
  if ($xmlrpcurl) { $ENV { 'TBTS_XMLRPC_URL' } = $xmlrpcurl ; $TBConfig::XMLRPC_SERVER = $xmlrpcurl ; }
  use TBConfig;
  if ($concurrent_prerun_jobs) { $TBConfig::concurrent_prerun_jobs = $concurrent_prerun_jobs; }
  if ($concurrent_node_usage) { $TBConfig::concurrent_node_usage = $concurrent_node_usage; }
  if ($cmdline_defines) { $TBConfig::cmdline_defines = $cmdline_defines; }
  if ($exclude_steps) { $TBConfig::exclude_steps = [split(/ /, $exclude_steps)]; }
  if ($single) { $TBConfig::single = $single; }
}

sub usage {
  our $ts;
  our $tpms;
  sub scandir_t     { if (-f && /\.t$/)  { $ts   .= "        " . $File::Find::name . "\n"; } }
  sub scandir_tests { if (-f && /\.pm$/) { $tpms .= "        " . $File::Find::name . "\n"; } }
  use File::Find;
  find(\&scandir_t, 't');
  find(\&scandir_tests, 'tests');
=pod old options
        -j --jobs=i    parallel jobs
        -t --timing
        -v --verbose
=cut
  print <<"USAGE";
TestBed TestSwap
./tbts OPTIONS TESTSUITE|TESTFILE
        -d --debug
        -g --group=GROUPNAME
        -p --project=PROJECTNAME
        -x --xmlrpcurl=XMLRPCURL
        --define OS=FBSD410-UPDATE
        --cprj=4  => \$concurrent_prerun_jobs,
        --cnu=20  => \$concurrent_node_usage,
        --exsteps "swapout end"
        --exsteps "create swapin swapout end"
        --exsteps "run"

    TESTSUITES:
        test     - all topology tests
        sanity   - all framework utility and xmlrpc client modules test
        lib      - all framework utility tests
        xmlrpc   - all xmlrpc client modules tests
        
        critic   - runs perl critic on framework code

    TESTFILES:
USAGE
  print $ts;
  print $tpms;
}

use TestBed::Harness;
if (@ARGV) {
  my $cmd = $ARGV[0];
  $_   = $cmd;
  chomp $_;
  if (/.*\.t$/ || /.*\.pm$/) { runharness(@ARGV); }
  elsif ($_ eq 'podc')      { system 'for x in `find lib -iname "*.pm"`; do podchecker $x 2>&1 |grep contain; done; '; }
  elsif ($_ eq 'pode')      { system 'for x in `find lib -iname "*.pm"`; do podchecker $x 2>&1 |grep ERROR; done;'; }
  elsif ($_ eq 'pode')      {
    eval "use Pod::Coverage;";
    unless ($@) {
      my $pc = Pod::Coverage->new(package => 'Pod::Coverage');
      print "We rock!" if $pc->coverage == 1;
    }
  }
  elsif (/critic/)          { exec 'perlcritic lib t'; }
  elsif (/sanity/)          { runharness( qw(t/lib/*.t t/lib/*/*.t t/xmlrpc/*.t) ); }
  elsif (/lib/)             { runharness qw(t/lib/*.t t/lib/*/*.t); }
  elsif (/xmlrpc/)          { runharness qw(t/xmlrpc/*.t); }
  elsif (/test/)            { runharness qw(t/topologies/*.t); }
  elsif (/coding/)          { runharness qw(t/coding/pod_coverage.t); }
}
else {
  print usage();
}

