#!/usr/bin/perl -w -T

($level, $runpath, $varpath, $logpath, $hosts, $nodes) = @ARGV;

open HOSTS, ">hosts.txt";
@hostList = split(",", $hosts);
print HOSTS join("\n", @hostList);
close HOSTS;

if (! defined($nodes)) {
	$nodes = $hosts;
}

$command = "pssh -h hosts.txt -o out -e err -t 3000 sh $runpath/standalone.sh $level $runpath $varpath $logpath $nodes";

system($command);
