#!/usr/bin/perl

# Location of ssh program
$ssh = "/usr/local/bin/ssh";

# Remote host to connect to
$host = "paper.cs.utah.edu";

# String to turn off password authentications
$nopass = "-o 'BatchMode yes'";

# Turn off host key checking.... for now.
$nokeycheck = "-o 'StrictHostKeyChecking No'";

# Current working directory:
$cwd = $ENV{PWD};
# Now, do the magic
$rv = system "$ssh $host $nopass $nokeycheck dir=$cwd $0 @ARGV";
if ($rv > 256) {
	print "SSH failed. You may need to run the following commands:\n";
	print "mkdir $ENV{HOME}/.ssh\n";
	print "ssh-keygen -P '' -f $ENV{HOME}/.ssh/identity\n";
	print "cp $ENV{HOME}/.ssh/identity.pub $ENV{HOME}/.ssh/authorized_keys\n";
}
