#!/usr/bin/perl

# Location of ssh program
if (-x "/usr/local/bin/ssh" ) {
	$ssh = "/usr/local/bin/ssh";
} elsif (-x "/usr/bin/ssh" ) {
	$ssh = "/usr/bin/ssh";
} else {
	die "Unable to find ssh - please send mail to testbed-ops\@fast.cs.utah.edu\n";
}

# Remote host to connect to
$host = "boss.emulab.net";

# String to turn off password authentications
$nopass = "-o 'BatchMode yes'";

# Turn off host key checking.... for now.
$nokeycheck = "-o 'StrictHostKeyChecking no'";

# Make sure we use the right identity file
$identity = "-i $ENV{HOME}/.ssh/identity";

# Current working directory:
$cwd = $ENV{PWD};
# We only want to actually change to $CWD if it will actually
# be accesible on the other machine - if it's in /users or /proj
if (!($cwd =~ qr|/users|) && !($cwd =~ qr|/proj|)) {
	warn "In order to make sure that this command has access to any\n";
	warn "files it may need to read, please change directories into\n";
	warn "your home directory (in /users/) or your project directory\n";
	warn "(in /proj/).\n";
	exit (-1);
}

# Now, do the magic
$sshcmd = "$ssh $identity $nopass $nokeycheck $host 'cd $cwd \; $0 @ARGV'";
#print "About to run $sshcmd\n";
$rv = system $sshcmd;

if ($rv > 256) {
	print "**********\n";
	print "SSH failed. You may need to run the following commands:\n\n";
	print "mkdir -m 0755 $ENV{HOME}/.ssh\n";
	print "ssh-keygen -P '' -f $ENV{HOME}/.ssh/identity\n";
	print "cp $ENV{HOME}/.ssh/identity.pub $ENV{HOME}/.ssh/authorized_keys\n";
	print "chmod 600 $ENV{HOME}/.ssh/authorized_keys\n";
	print "**********\n";
}
