#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2003 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

NODETYPE=`nodetype`
case $NODETYPE in
pc300|pc1500|pc2000|pc2400-aero)
    echo 'eth0'
    ;;
i2)
    echo 'eth1'
    ;;
pc850|pcL440GX)
    echo 'eth2'
    ;;
pc600|pc850a)
    echo 'eth4'
    ;;
*)
    echo 'unknown';
    ;;
esac
