#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2003 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

NODETYPE=`nodetype`
case $NODETYPE in
pc300|pc1500|pc2000)
    echo 'eth0'
    ;;
pc850)
    echo 'eth2'
    ;;
pcL440GX)
    echo 'eth2'
    ;;
pc600)
    echo 'eth4'
    ;;
*)
    echo 'unknown';
    ;;
esac
