#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2004, 2005 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

#
# Sweet! dhclient on linux wants to DHCP on the loopback interface
# thus screwing up its default setting.  Put a stop to that early on!
#
if [ xxx$interface = xxxlo ]; then
    exit_status=1
    return
fi

if [ x$reason != xREBOOT -a x$reason != xBOUND -a x$reason != xRENEW -a x$reason != xREBIND ]
then
    return
fi

#
# ElabinElab support.
#
if [ "$new_host_name" = "" ]; then
    #
    # If no hostname provided, it means that its an outer emulab returning
    # DHCPD info, in which case we want to again ignore most of the
    # info since all we want to do is configure the interface. 
    #
    new_static_routes="$new_dhcp_server_identifier $new_routers"
    unset new_domain_name_servers
    unset new_domain_name
    unset new_routers
    #
    # Ack, changed my mind. This is a pain in the ass. For now do not
    # configure the outer interface; worry about it later.
    # XXX sleep here so we don't pummel boss with REQUEST/DECLINE pairs.
    #
    sleep 5
    exit_status=1
elif [ "$new_network_number" = "10.200.1.0" ]; then
    #
    # I am inside an inner elab, force 100Mb full-duplex
    # since that is what the switch does
    #
    # XXX Linux dhclient-script doesn't support "media" so we do it
    # ourselves.
    #
    if /sbin/ethtool $interface >/dev/null 2>&1; then
      /sbin/ethtool -s $interface autoneg off speed 100 duplex full
    else
      /sbin/mii-tool --force=100baseTx-FD $interface
    fi >$LOGDIR/dhclient-enter.log 2>&1
fi
