#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2004 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

#
# A note about Linux. Redhat 9.0 appears to use dhclient instead of pump.
# We maintain/install both variants though to make life easier. 
#

date > $LOGDIR/dhclient.log
echo "$reason" >> $LOGDIR/dhclient.log

#
# Remember our server IP, real hostname, router IP, etc.
#
if [ x$reason = xREBOOT ] || [ x$reason = xBOUND ] || \
   [ x$reason = xRENEW ] || [ x$reason = xREBIND ]; then
    echo $new_dhcp_server_identifier > $BOOTDIR/bossip
    echo $new_host_name > $BOOTDIR/realname
    echo $new_routers > $BOOTDIR/routerip
    echo $new_ip_address > $BOOTDIR/myip
    echo $new_subnet_mask > $BOOTDIR/mynetmask
    if [ -n "$interface" ]; then
	echo $interface > $BOOTDIR/control_interface
    fi

    #
    # See if the Testbed configuration software wants to change the hostname.
    # 
    $BINDIR/sethostname.dhclient >>$LOGDIR/dhclient.log 2>&1
fi  

exit 0
