#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2003 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

if [ -x $BINDIR/cpuspeed.awk ]; then
	cpuspeed=`$BINDIR/cpuspeed.awk /proc/cpuinfo`;
else
	cpuspeed='';
fi

if [ x$cpuspeed = x ] || [ $cpuspeed = 0 ]; then
	echo "unknown";

# XXX hack for minibed and buff pc600s
elif [ $cpuspeed = "850" -a -x $BINDIR/chipset.awk -a -e /proc/pci ]; then
    case `$BINDIR/chipset.awk /proc/pci` in
    BX)
	echo pc850	# normal pc850
	;;
    GX)
	echo pcL440GX	# minibed node
	;;
    BX-AGP)
	echo pc850a    # buff pc600 node
	;;
    *)
	echo unknown
   	;;
esac
# For Aerospace Corp nodes
elif [ $cpuspeed = "2400" ]; then
	echo pc${cpuspeed}-aero;
# For Wiconsin nodes - they have a different node typing scheme
elif [ $cpuspeed = "2500" ]; then
	echo i2;

else
	echo pc$cpuspeed;
fi
