#!/bin/sh

if [ -x '/etc/rc.d/testbed/cpuspeed.awk' ]; then
	cpuspeed=`/etc/rc.d/testbed/cpuspeed.awk /proc/cpuinfo`;
else
	cpuspeed='';
fi

if [ x$cpuspeed = x ] || [ $cpuspeed = 0 ]; then
	echo "unknown";

# XXX hack for minibed
elif [ $cpuspeed = "850" -a -x '/etc/rc.d/testbed/chipset.awk' ]; then
	if [ `/etc/rc.d/testbed/chipset.awk /proc/pci` = "GX" ]; then
		echo pcL440GX;
	fi

else
	echo pc$cpuspeed;
fi
