#!/usr/bin/perl -wT
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2002 University of Utah and the Flux Group.
# All rights reserved.
#

use English;

#
# Untaint path
#
$ENV{'PATH'} = '/bin:/sbin:/usr/bin:/usr/local/bin:/etc/rc.d/testbed';
delete @ENV{'IFS', 'CDPATH', 'ENV', 'BASH_ENV'};

#
# Load the OS independent support library. It will load the OS dependent
# library and initialize itself. 
# 
use lib "/etc/rc.d/testbed";
use libsetup;

#
# Then invoke the bootsetup routine in the library. All the work happens
# in there. 
#
bootsetup();

#
# Enable ICMP ping-of-death
#
liblocsetup::enable_ipod();

exit 0;
