#!/bin/bash

#
# testbed-shutdown - On shutdown, inform the testbed that we're going down
#

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
if [ ! -f /etc/sysconfig/network ]; then
    exit 0
fi

. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

RETVAL=0

# See how we were called.
case "$1" in
  start)
  	touch /var/lock/subsys/tbshutdown
	echo "Done"
	;;
  stop)
  	rm /var/lock/subsys/tbshutdown
	echo "Informing the testbed we're rebooting ..."
	/etc/rc.d/testbed/tmcc state REBOOTING
	RETVAL=$?
	;;
  status)
	echo "Peachy"
	;;
  restart)
	echo "Done"
	;;
  reload)
	echo "Done"
	;;
  *)
	echo "Usage: testbed {start|stop|restart|reload|status}"
	exit 1
esac

exit $RETVAL
