#!/bin/bash
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2007 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

#
# testbed       Do some testbed stuff,
#
# description:	On shutdown, it informs the testbed we are rebooting
#		and terminates any lingering daemons.

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
if [ ! -f /etc/sysconfig/network ]; then
    exit 0
fi

. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

RETVAL=0

# See how we were called.
case "$1" in
  start)
	# This stuff done from rc.local cause I cannot figure
	# out a way to log to the console instead of messages.
	# Note, /var/lock/subsys/testbed will be created at that time.
	;;
  stop)
  	rm /var/lock/subsys/testbed
	echo "Shutting down testbed daemons (some may fail)..."
	echo -n "  trafgen: "
	killproc trafgen
	echo
	echo -n "  program-agent: "
	killproc program-agent
	echo
	echo -n "  slothd: "
	killproc slothd
	echo
	echo -n "  healthd: "
	killproc healthd
	echo
	echo -n "  watchdog: "
	killproc watchdog
	echo
	echo -n "  evproxy: "
	killproc evproxy
	echo
	echo -n "  linktest: "
	killproc linktest
	echo
	echo -n "  emulab-syncd: "
	killproc emulab-syncd
	echo
	echo -n "  tippty: "
	killproc tippty
	echo
        if [ ! -f /var/lock/subsys/tbprepare ]; then
	    echo "Informing the testbed we're rebooting ..."
	    $BINDIR/tmcc state SHUTDOWN
	    RETVAL=$?
	fi
	;;
  status)
	echo "Peachy"
	;;
  restart)
	echo "Done"
	;;
  reload)
	echo "Done"
	;;
  *)
	echo "Usage: testbed {start|stop|restart|reload|status}"
	exit 1
esac

exit $RETVAL
