#!/bin/sh

#
# A little script to put the testbed ports into the ports tree
#

PORTSDIR=/usr/ports
PORTSUBDIR=misc
SRCDIR=`dirname $0`
PORTS="elvind emulab-boss emulab-fs emulab-ops libelvin emulab-tftp-hpa p5-GD-old ulsshxmlrpcpp emulab-iperf emulab-php4 emulab-mailman"

for PORT in $PORTS
do
    cp -r $SRCDIR/$PORT $PORTSDIR/$PORTSUBDIR
    if [ "$?" != "0" ]
    then
	exit 1
    fi
done

exit 0
