#!/bin/sh

#
# A little script to put the testbed ports into the ports tree
#

PORTSDIR=/usr/ports
PORTSUBDIR=misc
SRCDIR=`dirname $0`
PORTS="elvind emulab-boss emulab-fs emulab-ops libelvin emulab-tftp-hpa p5-GD-old p5-DBD-mysql50-old ulsshxmlrpcpp emulab-iperf emulab-php4 emulab-mailman emulab-pubsub emulab-pubsub-elvincompat emulab-clrhouse"

echo "Copying ports ..."
for PORT in $PORTS
do
    cp -r $SRCDIR/$PORT $PORTSDIR/$PORTSUBDIR
    if [ "$?" != "0" ]
    then
	exit 1
    fi
done

# "register" the emulab ports
echo "Patching $PORTSDIR/$PORTSSUBDIR/Makefile ..."
patch -p0 $PORTSDIR/$PORTSSUBDIR/Makefile ports.patch

## recreate the index
#echo "Recreating ports INDEX (this will take forever) ..."
#cd $PORTSDIR
#make index

echo "Done!"
exit 0
