#!/bin/sh

#
# A little script to put the testbed ports into the ports tree
#

PORTSDIR=/usr/ports
PORTSUBDIR=misc
SRCDIR=`dirname $0`
PORTS="elvind emulab-boss emulab-ops libelvin tftp-hpa"

for PORT in $PORTS
do
    cp -r $SRCDIR/$PORT $PORTSDIR/$PORTSUBDIR
    if [ "$?" ]
    then
	exit 1
    fi
done
