#!/bin/sh
timeit=/usr/bin/time

if [ ! -x ../extractmail.pl -o ! -x ../parsemail.pl -o ! -x ../checkrecords.pl -o ! -r tbmail.pm ]; then
    echo 'No scipts!  Wrong working directory?'
    exit 1
fi

mv filtered ofiltered
mv extract.log oextract.log
cat *.mail | $timeit ../extractmail.pl >filtered 2>extract.log || {
    echo 'extracttbmail failed!'
    mv oextract.log extract.log
    mv ofiltered filtered
    exit 1
}

mv records orecords
mv parse.log oparse.log
$timeit ../parsemail.pl <filtered >records 2>parse.log || {
    echo 'parsemail raw record generation failed!'
    mv oparse.log parse.log
    mv orecords records
    mv oextract.log extract.log
    mv ofiltered filtered
    exit 1
}

mv fixed ofixed
mv fixup.log ofixup.log
$timeit ../checkrecords.pl -f <records >fixed 2>fixup.log || {
    echo 'parsemail fixup failed!'
    mv ofixup.log fixup.log
    mv ofixed fixed
    mv oparse.log parse.log
    mv orecords records
    mv oextract.log extract.log
    mv ofiltered filtered
    exit 1
}

diff oextract.log extract.log | grep Saved >extract.diffs && {
    echo '*** WARNING: diffs in message extraction, see extract.diffs'
}
diff oparse.log parse.log | grep Processed >parse.diffs && {
    echo '*** WARNING: diffs in message parsing, see parse.diffs'
}
diff ofixed fixed >fixed.diffs || {
    echo '*** WARNING: diffs in fixed records, see fixed.diffs'
}

exit 0;
