#! /bin/sh

build_dir="$1"
target_dir="$2"
shift
shift
modules="$@"

install_file()
{
	local file="$1"
	local target="$2"

	local target_file="${file##*$build_dir/lib}"

	echo mkdir -p "$target_dir/${target_file%/*}"
	mkdir -p "$target_dir/${target_file%/*}"
	echo install -m 444 "$file" "$target_dir/$target_file"
	install -m 444 "$file" "$target_dir/$target_file"
}

for module in $modules; do
	module_file="$build_dir/lib/$module.pm"
	module_dir="$build_dir/lib/$module"
	auto_dir="$build_dir/lib/auto/$module"
	if [ -f "$module_file" ]; then
		install_file "$module_file" "$target_dir"
	fi

	if [ -d "$module_dir" ]; then
		find $module_dir -type f \! -name \*.t \! -iname README \
			\! -iname Changes \! -name .exists | while read f; do
			install_file "$f" "$target_dir"
		done
	fi

	# XXX If you want to use AutoLoader, remove the exceptions for
	# *.ix and *.al from the find command below
	if [ -d "$auto_dir" ]; then
		find $auto_dir -type f \! -name \*.t \! -name .exists \
			\! -name \*.al \! -name \*.ix | \
			while read f; do
			install_file "$f" "$target_dir"
		done
	fi
done
