#! /bin/sh
#
# hypview - Wrapper script for the hyperviewer application.
#
# EMULAB-COPYRIGHT
# Copyright (c) 2004 University of Utah and the Flux Group.
# All rights reserved.
#
# Permission to use, copy, modify and distribute this software is hereby
# granted provided that (1) source code retains these copyright, permission,
# and disclaimer notices, and (2) redistributions including binaries
# reproduce the notices in supporting documentation.
#
# THE UNIVERSITY OF UTAH ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
# CONDITION.  THE UNIVERSITY OF UTAH DISCLAIMS ANY LIABILITY OF ANY KIND
# FOR ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
#

# Optionally use shared libs under the local directory.
if [ -d libs ]; then
    if [ $LD_LIBRARY_PATH ]; then
        LD_LIBRARY_PATH=./libs:$LD_LIBRARY_PATH
    else
        LD_LIBRARY_PATH=./libs
    fi
    export LD_LIBRARY_PATH
fi

# Optionally use Pango loadable modules under the local directory.
if [ -d libs/pango ]; then
    PANGO_RC_FILE=./pangorc.local; export PANGO_RC_FILE
fi

# If the wxPython or OpenGL directories are local, they will be used.
python hypview.py $*
