#!/usr/bin/perl -w

# This program should be run after assign_wrapper/assign has run and the
# resources have been reserved.  This updated the delays table and the
# vname column in the reserved table.

push(@INC,"/usr/testbed/lib/tbsetup/ir");
require libir;

if ($#ARGV != 0) {
    print STDERR "Syntax: $0 irfile\n";
    exit (1);
}
$irfile = $ARGV[0];

use DBI;

$driver = "mysql";
$dbh = DBI->connect("DBI:$driver:database=tbdb;host=localhost") 
    || die "Could not connect to DB.\n";


eval {&ir_read($irfile)};
if ($@) {
    print STDERR "Could not read $irfile ($@)\n";
    exit(1);
}

# Update vnames
$raw = eval {&ir_get("/virtual/nodes")};
if ($@) {
    print STDERR "Could not load /virtual/nodes.\n";
    exit(1);
}
foreach (split("\n",$raw)) {
    ($vnode,$pnode) = split;
    $sth = $dbh->prepare("UPDATE reserved SET vname = \"$vnode\" WHERE node_id = \"$pnode\"");
    $sth->finish;
}

# Update delays
$raw = eval {&ir_get("/delay")};
if ($@) {
    print STDERR "Could not read /delay.\n";
    exit(1);
}
foreach (split("\n",$raw)) {
    ($node,$bw,$latency,$loss,$macA,$macB) = split;
    
    $sth = $dbh->prepare("SELECT card FROM interfaces WHERE mac = \"$macA\"");
    $sth->execute;
    ($int0) = $sth->fetchrow_array;
    $sth->finish;

    $sth = $dbh->prepare("SELECT card FROM interfaces WHERE mac = \"$macB\"");
    $sth->execute;
    ($int1) = $sth->fetchrow_array;
    $sth->finish;

    $sth = $dbh->prepare("DELETE FROM delays WHERE node_id = \"$node\"");
    $sth->execute;
    $sth->finish;

    $sth = $dbh->prepare("INSERT INTO delays (node_id,card0,card1,delay,bandwidth,lossrate) VALUES (\"$node\",$int0,$int1,$latency,$bw,$loss)");
    $sth->execute;
    $sth->finish;
}
