#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2011 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

# Why am I trying to fix this script!?
if [ -r $BOOTDIR/nodeid -a -r $BOOTDIR/ltpmap ]; then
    nid=`cat $BOOTDIR/nodeid`
    nt=`grep $nid $BOOTDIR/ltpmap 2>/dev/null | awk "/^H/ { if (\\$3 == \"$nid\") print \\$5 }" 2>/dev/null`
    if [ -n "$nt" ]; then
	echo $nt
	exit 0
    fi
fi

# XXX for FreeBSD 5.x
if [ ! -r /var/run/dmesg.boot ]; then
	dmesg > /var/run/dmesg.boot
fi

if [ -x $BINDIR/cpuspeed.awk ]; then
	cpuspeed=`$BINDIR/cpuspeed.awk /var/run/dmesg.boot`;
else
	cpuspeed='';
fi

if [ x$cpuspeed = x ] || [ $cpuspeed = 0 ]; then
	echo "unknown";

# XXX hack for minibed and buff pc600s
elif [ $cpuspeed = "850" -a -x $BINDIR/chipset.awk ]; then
    case `$BINDIR/chipset.awk /var/run/dmesg.boot` in
    BX)
	echo pc850	# normal pc850
	;;
    GX)
	echo pcL440GX	# minibed node
	;;
    BX-AGP)
	echo pc850a    # buff pc600 node
	;;
    *)
	echo unknown
   	;;
    esac
# For Aerospace Corp and Rutgers nodes
elif [ $cpuspeed = "2400" -a -x $BINDIR/chipset.awk ]; then
    case `$BINDIR/chipset.awk /var/run/dmesg.boot` in
    HI_C)
	echo pc${cpuspeed}-aero;
	;;
    HI_B)
	echo pc${cpuspeed}-orbit;
	;;
    *)
	echo unknown
   	;;
    esac
# For Wiconsin nodes - they have a different node typing scheme
elif [ $cpuspeed = "2500" ]; then
	echo i2;

else
	echo pc$cpuspeed;
fi

exit 0
