#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2002 University of Utah and the Flux Group.
# All rights reserved.
#

mysql --execute="delete from node_idlestats" tbdb && \
mysql --execute="delete from iface_counters" tbdb
