#!/bin/bash
#
# EMULAB-COPYRIGHT
# Copyright (c) 2004 University of Utah and the Flux Group.
# All rights reserved.
#
# Stop the current the SSH daemon.

pidfile=/var/run/sshd.pid
upidfile=$pidfile.user
running=
if [ -e $upidfile ]; then
    # Check that the process ID actually refers to a running process. 
    pid=`cat $upidfile`
    if ( kill -0 $pid >& /dev/null ); then
	running=yes
    fi
fi
if [ $running ]; then
    if ( ps -u SYSTEM | grep -q "^ *$pid " ); then
        echo "Ignoring SYSTEM sshd."
    else
        echo "Killing sshd daemon."
        ps -ef | awk '$2=='$pid'{print}'
        kill $pid
    fi
fi
