# -*- tcl -*-
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2003 University of Utah and the Flux Group.
# All rights reserved.
#

######################################################################
# vtype.tcl
#
# This defines the Vtype class.  Unlike other classes, Vtypes are 
# testbed specific.  They are generated by the tb-make-*-vtype 
# command.  A Vtype contains a list of types.  Nodes can also have
# Vtypes as their types.  Finally, a Vtype has a weight.
######################################################################

Class Vtype

Vtype instproc init {w t} {
    $self set types $t
    $self set weight $w
}

Vtype instproc updatedb {DB} {
    var_import ::GLOBALS::pid
    var_import ::GLOBALS::eid
    $self instvar name
    $self instvar types
    $self instvar weight

    spitxml_data "virt_vtypes" [list "name" "weight" "members" ] [list $self $weight $types ]
}

