#!/usr/local/bin/perl -w

if ($#ARGV < 0) {die("Usage: mac2if <mac|if> <mac|if> <...>\n");}

use Mysql;

my $dbh = Mysql->connect("localhost","tbdb","script","none");

my @list = "";
my $n=0;
foreach my $mac ( @ARGV ) { 
  if ( $mac =~ /^(sh\d+)(-\d)?(:\d)?$/ ) {
    my $node = $1. (defined $2 ? $2 : "-" );
    $list[$n] .= "(node_id like '$node%')";
  } elsif ( $mac =~ /^([a-zA-Z]+\d+):(\d+)$/ ) {
    my $node=$1;
    my $if=$2;
    $list[$n] .= "(node_id='$node' and card='$if')";
  } elsif ( $mac =~ /^([a-zA-Z]+\d+)$/ ) {
    my $node=$1;
    $list[$n] .= "(node_id='$node')";
  } else {
    $mac =~ s/^(\d):/0$1:/;
    $mac =~ s/:(\d):/:0$1:/g;
    $mac =~ s/://g;
    $list[$n] ="MAC='\L$mac'";
  }
  $n++;
}

my $cond = join(" or ",@list);

#print "Using conditions '$cond'\n";

my $sth = $dbh->
    query("select * from interfaces where $cond");

print $sth->as_string();
