#!/usr/local/bin/perl -w
use Mysql;
use English;

my $dbh = Mysql->connect("localhost","tbdb","script","none");

if ($#ARGV < 1) {die("Usage: nalloc <pid> <eid> <node> <node> <...>\n");}

my $TB="/usr/testbed/bin";
my $consetup="$TB/console_setup";
my $error = 0;
my $pid = shift;
my $eid = shift;
my @node_names=@ARGV;
my @machines = @node_names;
foreach my $m (@machines) { $m = "node_id='".$m."'"; }
my $list= join(" or ",@machines);

my $cmd = "";
my $sth = "";

my $self = (getpwuid($UID))[0]
  || die "Cannot figure out who you are!\n";

$cmd = "select uid from proj_memb as pm left join experiments as e on ".
  "e.pid=pm.pid where e.eid='$eid' and uid='$self' and e.pid='$pid'";
$sth = $dbh->query($cmd);
if ( ($sth->numrows < 1) && ($UID != 0) && ($EUID != 0)) {	
  die("You are not a member of experiment '$eid' in project '$pid'.\n");
}
 
foreach my $n (@node_names) { 
  $sth = $dbh->query("select * from reserved where node_id='$n'");
  if ($sth->numrows > 0) {
    $cmd="select * from reserved where node_id='$n' and eid='$eid' and pid='$pid'";
    $sth = $dbh->query($cmd);
    if ($sth->numrows > 0) {	
      print "You have already reserved node '$n'.\n";
      # Do not increment error code since that throws off tbprerun.
    } else {
      print "Someone else has already reserved node '$n'.\n";
      $error++;
    }
    next;
  } else {
    $sth = $dbh->query("select * from nodes where node_id='$n'");
    if ($sth->numrows < 1) {	
      print "Node '$n' does not exist.\n";
      $error++;
      next;
    }
  }
  print "Reserving node '$n'...";
  $cmd = "insert into reserved (node_id,pid,eid) values ('$n','$pid','$eid')";
  $sth = $dbh->query($cmd) && print "Succeeded.\n"
    || (print "Failed Command:\n$cmd\nError string is:".$dbh->errstr."\n"
      && $error++);
  system("$consetup $n") == 0 or
      print STDERR "WARNING: $consetup $n failed!";
}

exit($error);
