#!/usr/local/bin/perl -w
use Mysql;

my $dbh = Mysql->connect("localhost","tbdb","script","none");

if ($#ARGV < 1) {
  die("Usage: nfree <pid> <eid> [<node> <node> <...>]\n".
      "Releases all nodes in the specified experiment. If nodes are listed,\n".
      "nfree releases only the listed nodes.\n");
}

my $error = 0;
my $pid = shift;
my $eid = shift;
my @node_names=@ARGV;
my @machines = @node_names;
foreach my $m (@machines) { $m = "node_id='".$m."'"; }
my $list= join(" or ",@machines);

my $cmd = "";
my $sth = "";

$cmd = "select * from experiments where eid='$eid' and pid='$pid'";
$sth = $dbh->query($cmd);
if ($sth->numrows < 1) {	
  die("There is no experiment '$eid' in project '$pid'.\n");
}
 
# If list is empty, put in all the nodes
if ($#node_names == -1) {
  print "Releasing all nodes from experiment '$eid' in project '$pid'...\n";
  $sth = $dbh->
    query("select node_id from reserved where pid='$pid' and eid='$eid'");
  while (@row = $sth->fetchrow_array()) {
    push(@node_names, $row[0]);
  }
}

foreach my $n (@node_names) { 
    $sth = $dbh->query("select * from reserved where node_id='$n' ".
		       "and eid='$eid'");
    if ($sth->numrows == 0) {
	print "Node '$n' is not reserved by your experiment.\n";
	$error++;
	next;
    } 
    print "Releasing node '$n'...";
    $cmd = "delete from reserved where node_id='$n' and eid='$eid'";
    $sth = $dbh->query($cmd) && print "Succeeded.\n"
	|| (print "Failed Command:\n$cmd\nError string is:".$dbh->errstr."\n"
	    && $error++);
    
    # Find the control net interface for this node type
    $sth = $dbh->query("select control_net from node_types as t left join ".
		       "nodes  as n on n.type=t.type where node_id='$n'");
    my @row= $sth->fetchrow_array();
    my $control= $row[0];
    print "Got Control $control\n";
    $cmd = "update interfaces set IP='' where node_id='$n' and card!='$control'";
    $sth = $dbh->query($cmd)
	|| (print "Failed Command:\n$cmd\nError string is:".$dbh->errstr."\n"
	    && $error++);
}

exit($error);
