#!/usr/local/bin/perl -w
#
# Generates a ptop file from the output of an avail command.
# Takes input on STDIN and output goes to STDOUT
#

use Mysql;
my $dbh = Mysql->connect("localhost","tbdb","script","none");

my $d = 0; #debug
my %nodes = ();
my %links = ();
my $node;

while (<>) {
  if (!/^\|/ ) {next;}
  if ( /^\|node_id/) {next;}
  /^\|([a-zA-Z0-9-]*) *\|/;
  $node=$1;
  if ($node =~/tbpc|tbsh/) {
    $nodes{$node} = 1;
    print STDERR "Got '$node' \t" if $d;
  }
}

print STDERR "\n" if $d;

my @list = sort keys %nodes;
foreach my $item (@list) { 
  print STDERR "From '$item'\t" if $d;
  $item = "node_id='$item'"; 
  print STDERR "To '$item'\n" if $d;
}
my $cond = join (" or ",@list);

my $query = "select node_id,card,MAC from interfaces where $cond";

print STDERR "Using query '$query'\n" if $d;

my $sth = $dbh->query($query);

while (my @row = $sth->fetchrow()) {
  if ( $row[0] =~ /tbpc/ ) {
    $links{$row[0]."-".$row[1]} = $row[2];
  } else {
    $links{$row[0]} = $row[2];
  }
}

# In every ptop
print "node cisco switch\n";

# Give the nodes:
foreach $node (sort keys %nodes) {
  if ($node =~ /tbpc/) {
    print "node $node pc:1 delay:1\n";
    print "link $node-0 $node:$links{$node.'-0'} cisco 100 1\n";
    print "link $node-1 $node:$links{$node.'-1'} cisco 100 1\n";
    print "link $node-2 $node:$links{$node.'-2'} cisco 100 1\n";
    print "link $node-3 $node:$links{$node.'-3'} cisco 100 1\n";
  } else {
    print "node $node shark-shelf:1\n";
    print "link $node $node:$links{$node} cisco 100 1\n";
  }
}
