#!/usr/local/bin/perl -w

use DBI;
$driver = "mysql";
$dbh = DBI->connect("DBI:$driver:database=tbdb;host=localhost")
    || die "Could not connect.\n";

if ($#ARGV >= 1) {
    ($oper, @usrs) = @ARGV;
    if ($oper eq '-r') {
	foreach $n (@usrs) {
	    chomp($n);
	    $sth = $dbh->prepare("DELETE FROM users WHERE uid = \"$n\"");
	    $sth2 = $dbh->prepare("DELETE FROM grp_memb WHERE uid = \"$n\"");
	    $sth3 = $dbh->prepare("DELETE FROM proj_memb WHERE uid = \"$n\"");
	    $rr = $sth->execute;
	    $rr == 0 && die "User $n not found.\n";
	    $sth2->execute;
	    $sth3->execute;
	    print "User $n removed.\n"; 
	}
    } elsif ($oper eq '-a') { 
	foreach (@usrs) {
	    print "User expires: ";
	    chomp($usr_expires = <STDIN>);
	    print "User name: ";
	    chomp($usr_name = <STDIN>);
	    print "User email: ";
	    chomp($usr_email = <STDIN>);
	    print "User address: ";
	    chomp($usr_addr = <STDIN>);
	    print "User phone number: ";
	    chomp($usr_phones = <STDIN>); 
	    print "Trust level: ";
	    chomp($trust_level = <STDIN>);
	    $sth = $dbh->prepare("INSERT INTO users VALUES ('$_', now(), '$usr_expires', '$usr_name', '$usr_email', '$usr_addr', '$usr_phones', '$trust_level')");
	    $ra = $sth->execute;
	    $ra == 0 || print "User $usr_name added.\n";
	}
    } else {
	print "Incorrect command: \"-r\" or \"-a\" expected.\n";
    }
} else {
    print "Type the command \"-r\" and a username to remove an user from the database or \"-a\" and a user ID to add a new user to the database.\n";
}


