.\"
.\" EMULAB-COPYRIGHT
.\" Copyright (c) 2004, 2005, 2006 University of Utah and the Flux Group.
.\" All rights reserved.
.\"
.TH LOGHOLE 1 "June 16, 2005" "Emulab" "Emulab Commands Manual"
.OS
.SH NAME
loghole \- Log management tool for experiments.
.SH SYNOPSIS
.BI loghole
[\fB-hVdqva\fR]
[\fB-e \fIpid\fR/\fIeid\fR]
[\fB-s \fIserver\fR]
[\fB-P \fIport\fR]
.I action
[\fI...\fR]
.P
.BI loghole
.BI sync
[\fB-nPs\fR]
[\fB-r \fIremotedir\fR]
[\fB-l \fIlocaldir\fR]
[\fInode1 node2 ...\fR]
.P
.BI loghole
.BI validate
.P
.BI loghole
.BI archive
[\fB-k \fR(\fBi-delete\fR|\fBspace-is-needed\fR)]
[\fB-a \fIdays\fR]
[\fB-c \fIcomment\fR]
[\fB-d\fR]
[\fIarchive-name\fR]
.P
.BI loghole
.BI change
[\fB-k \fR(\fBi-delete\fR|\fBspace-is-needed\fR)]
[\fB-a \fIdays\fR]
[\fB-c \fIcomment\fR]
.I archive-name1
[\fIarchive-name2 ...\fR]
.P
.BI loghole
.BI list
[\fB-O1!Xo\fR]
[\fB-m \fIatmost\fR]
[\fB-s \fImegabytes\fR]
.P
.BI loghole
.BI show
[\fIarchive-name\fR]
.P
.BI loghole
.BI clean
[\fB-fne\fR]
[\fInode1 node2 ...\fR]
.P
.BI loghole
.BI gc
[\fB-n\fR]
[\fB-m \fIatmost\fR]
[\fB-s \fImegabytes\fR]
.SH DESCRIPTION
The
.B loghole
utility downloads log files from certain directories on the experimental nodes
(e.g. "/local/logs") to the Emulab
.I users
machine.  After downloading, it can
also be used to produce and manage archives of the log files.  Using this
utility to manage an experiment's log files is encouraged because it will
transfer the logs in a network-friendly manner and is already integrated with
the rest of Emulab.  For example, any programs executed using the Emulab
event-system will have their standard output/error automatically placed in the
"/local/logs" directory.  The tool can also be used to preserve multiple trials
of an experiment by producing and managing zip archives of the logs.
.P
The set of logs that are actually downloaded by the tool are those located in
.I logholes
on the nodes, where a loghole is simply a well-known directory that acts like a
blackhole for log files.  Any files found in these directories are downloaded
to the experiment's log directory (i.e. "/proj/<pid>/exp/<eid>/logs") and
placed under separate directories for each node and loghole.  The referent of
symbolic links are also downloaded, so if you do not want an entire directory
downloaded, you can create links in a loghole to those files of interest.
.P
To perform its various tasks, the
.B loghole
utility is broken up into several sub-actions that you can apply to an
experiment's log holes or log archives.  As a quick example, to synchronize the
logholes for the experiment "neptune/myexp" and create an archive of these logs
you would run:
.RS
.P
.PD 0
[vmars@users ~] loghole -e neptune/myexp sync
.PP
[vmars@users ~] loghole -e neptune/myexp archive
.PD
.RE
.P
The following listing gives a brief overview of the current set of actions,
more detail can be found in later sections of this manual:
.TP
.B sync
Synchronize the experiment's log holes on the nodes with the experiment's log
directory.
.TP
.B validate
Validate that the logs were sync'd correctly by performing some sanity checks.
.TP
.B archive
Archive the contents of the experiment's log directory into a zip file.
.TP
.B change
Change the metadata of an existing archive.
.TP
.B list
Print a brief listing of the archives in the experiment's log directory.
.TP
.B show
Print a detailed listing of the archives in the experiment's log directory.
.TP
.B clean
Clean out the experiment log directory by removing any subdirectories and/or
clean the log directories on the nodes.
.TP
.B gc
Garbage collect old archives to free up disk space.
.P
Options passed to the utility are split between globally applicable ones that
are placed before the action and action-specific options that are placed after.
For example, the
.B -a
global option will apply an action to all of your experiments and the
.B -X
option for the
.B list
action will list only those files that will be deleted at the next garbage
collection.  To combine these options you would enter:
.RS
.P
[vmars@users ~] loghole -a list -X
.RE
.P
The set of global options is as follows:
.TP
\fB-h\fR, \fB--help
Print the usage message for the
.B loghole
utility as a whole or, if an action is given, the usage message for that
action.
.TP
\fB-V\fR, \fB--version
Print out version information and exit.
.TP
\fB-d\fR, \fB--debug
Output debugging messages.
.TP
\fB-q\fR, \fB--quiet
Decrease the level of verbosity, this is subtractive, so multiple uses of this
option will make the utility quieter and quieter.  The default level of
verbosity is human-readable, below that is machine-readable, and below that is
silent.  For example, the default output from the "list" action looks like:
.P
.RS
.RS
.PD 0
[ ] foobar.1.zip   10/15
.P
[!] foobar.0.zip   10/13
.RE
.PD
.P
Using a single "-q" option changes the output to look like:
.P
.RS
.PD 0
foobar.1.zip
.P
foobar.0.zip
.RE
.PD
.RE
.TP
\fB-e\fR, \fB--experiment\fR=\fIPID\fR/\fIEID\fR
Specify the experiment(s) to operate on.  If multiple
.B -e
options are given, the action will apply to all of them.  This option overrides
the default behavior of inferring the experiment from the current directory
(see the ENVIRONMENT section).
.TP
\fB-a\fR, \fB--all
Perform the action on all existing experiments that you have created.
.TP
\fB-s\fR, \fB--server\fR=\fISERVER
Specify the XML-RPC server to contact for information about the experiment.
Normal users should not have to use this option.
.TP
\fB-P\fR, \fB--port\fR=\fIPORT
Specify the XML-RPC server port to contact for information about the
experiment.  Normal users should not have to use this option.
.P
.SH SYNC
The
.B sync
action is used to synchronize the logholes on the nodes with the experiment's
log directory on the Emulab users machine.  The action will iterate through
each node in the experiment and perform an rsync(1) on the loghole directories
for that node.  Currently, the default set of directories that will be synced are "/var/emulab/logs"
and "/local/logs".  In addition, if any of the network links in the experiment
are being traced,
.B loghole
will perform the following extra steps:
.TP
1.
Create a directory for each link.
.TP
2.
Setup symbolic links to the pcap(3) files retrieved from the delay nodes.
.TP
3.
Run the pre-shaped pcap(3) files (e.g. *.recv.0) through tcptrace(1) to generate
graphs viewable with xplot(1).  Note that the processing will only be done for
pcap files that were generated by a SNAPSHOT event sent to the tracemon agent.
The "-s" option is provided to automatically send this event for each agent.
.P
While the download is in progress,
.B loghole
will display some simple statistics.  The left-hand side of the display shows
the number of nodes remaining to be synced, in progress, and completed.  The
right-hand side shows minimum, average, and maximum amount of time needed to
sync a node.  Finally, a "spinner" on the far right is updated when the
currently active rsync log files have grown, which usually happens when more
files are being synced.
.P
If rsync(1) encounters an error while running, it will automatically be rerun
after a short delay.
.P
Optional arguments:
.TP
\fB-r\fR, \fB--remote\fR=\fIremotedir
An additional remote directory to sync.  This option is additive, so you can
download several additional directories.
.TP
\fB-l\fR, \fB--local\fR=\fIlocaldir
The local directory to store the downloaded files.  This defaults to the
experiment's log directory.
.TP
\fB-n\fR, \fB--no-standard
Flag that indicates that the standard logholes (i.e. "/var/emulab/logs",
"/local/logs") should not be downloaded.
.TP
\fB-P\fR, \fB--no-post
Do not do any additional post-processing of the log files.  Currently, the only
post-processing is done on the pcap files generated by the link trace agents.
.TP
\fB-s\fR, \fB--snapshot
Send a SNAPSHOT event to the link trace agents before syncing the logfiles.
This is mostly a convenience so you do not have to remember to send the event
before gathering the files.
.TP
.I node1 ...
Specify a subset of virtual or physical nodes that should be synchronized,
otherwise all of the nodes will be synchronized.
.SH VALIDATE
The
.B validate
action is used to check that the logs were sync'd correctly.  Currently, the
following checks are performed:
.TP
program-agent logs
The stdout and stderr logs from program agents are checked by comparing their
metadata against that saved in the accompanying ".status" files.
.TP
valid soft links
All soft links are checked to ensure the referent exists.
.SH ARCHIVE
The
.B archive
action is used to archive the logs in an experiment's log directory for future
reference.  The action will produce a standard zip archive with the logs and
some metadata about the experiment and when it can be garbage collected.
.P
Available options:
.TP
\fB-k\fR, \fB--keep-until\fR=(\fIi-delete\fR|\fIspace-is-needed\fR)
Keep the archive until you decide to delete it manually or space is needed.
See the GC section later in the manual to learn how this option and others
affect garbage collection.  (Default: space-is-needed)
.TP
\fB-a\fR, \fB--keep-atleast\fR=\fIN
Keep the archive atleast
.I N
days after creation.  This value keeps the archive from being garbage collected
when more space is needed for atleast the given number of days.  (Default: 3
days)
.TP
\fB-c\fR, \fB--comment\fR=\fICOMMENT
Add a comment to the archive.  This option can be used multiple times to add
more than one comment to the archive.  The comments will be displayed by the
.I show
action and can be useful for storing information about the experiment, for
example, the input parameters.  If the argument to this option is is a single
dash (\fB-\fR) the comment will be read from standard in.
.TP
\fB-d\fR, \fB--delete
After creating the archive, mark the experiment as
.I clean-on-sync
so that any stale data is cleaned out before performing the next
.B sync
operation.  Currently, the mark is a file named ".cleanonsync" in the
experiment log directory.
.SH CHANGE
The
.B change
action is used to change the metadata of an existing archive.  For example, if
after analyzing the log files, you decide that they represent "good" data, you
can add a comment stating that fact and mark the archive as not garbage
collectable.  The action takes the same set of options as the
.B archive
action.
.SH LIST
The
.B list
action is used to get a brief summary of all of the log archives found in an
experiment's log directory.  The listing displays the archive name, when it was
created, and its GC status so you can get an idea of when the experiment runs
were performed and what will be garbage collected.
.TP
.B -O
Only list archives that are marked as 'keep until "i-delete"'.
.TP
.B -1
Only list archives that are a day from their keep-atleast date.
.TP
.B -!
Only list archives that are past their keep-atleast date.
.TP
.B -X
Only list archives that are ready to be garbage collected.
.TP
.B -o
List archives that do not match the above flags.  In other words, archives that
will not be deleted at the next garbage collection and are more than a day away
from their keep-atleast dates.
.TP
\fB-m\fR, \fB--keep-atmost\fR=\fIN
Specify how many archives should be kept in the experiment.  This setting
effects what files will be garbage collected, so you should pass this same
option to the
.B gc
if you use a different value from the default of 100 archives.
.TP
\fB-s\fR, \fB--keep-size\fR=\fImegabytes
Specify the maximum total size, in megabytes, for all of the archives in the
experiment.  This setting effects what files will be garbage collected, so you
pass this same option to the
.B gc
if you use a different value from the default of 3MB.
.SH SHOW
The
.B show
action provides a more detailed listing of the log archives for an experiment.
The listing contains information about when and who created the archive, any
attributes used when computing the GC status of the archive, comments attached
to the archive, and a listing of the files in the archive.
.P
Optional arguments:
.TP
.I archive-name
The full or partial name of the archive to display.  If a partial name is
given, any archive names that start with the argument are displayed.  The
default behavior is to display all of the archives in an experiment.
.SH CLEAN
The
.B clean
action is used to clean out log files from the experiment's log directory and
the log directories on the nodes.  The default action is to ask confirmation
and then clean out all of the log files.
.P
Available
.B clean
options:
.TP
\fB-f\fR, \fB--force
Do not prompt for confirmation.
.TP
\fB-n\fR, \fB--nodes
Only remove log files on the nodes.
.TP
\fB-e\fR, \fB--experiment
Only remove log directories in the experiment's log directory.
.SH GC
The
.B gc
action is used to garbage collect any archives in order to free up space or
reduce the total number of archives in an experiment.  The process for
selecting files to be garbage collected is as follows:
.TP
1.
If the total number of archives and their total size are below the values
specified by the
.B --keep-atmost
and
.B --keep-size
options then no archives will be deleted, otherwise...
.TP
2.
Any files that are marked as 'keep until "space-is-needed"' and past their
"keep-atleast" dates, will be deleted until the keep-atmost and keep-size
conditions are met.  If deleting these files does not meet these conditions
then...
.TP
3.
The oldest files that are marked 'keep until "space-is-needed"' will be deleted
until the keep-atmost and keep-size conditions are met or there are no more
files that can be deleted without user intervention.
.P
Available
.B gc
options:
.TP
\fB-m\fR, \fB--keep-atmost\fR=\fIN
Specify how many archives should be kept in the experiment.  (Default: 100
archives)
.TP
\fB-s\fR, \fB--keep-size\fR=\fImegabytes
Specify the maximum total size, in megabytes, for all of the archives in the
experiment.  (Default: 3.0 MB)
.SH ENVIRONMENT
By default, the project and experiment ID will be inferred from the current
working directory, if it is inside the experiment's directory
(i.e. /proj/\fIpid\fR/exp/\fIeid\fR).  This behavior can be overridden using
the
.B -e
option.
.SH RETURN VALUES
.TP
3
If rsync reports an error.
.TP
2
If there was an error processing the command line arguments.
.TP
0
If the action was completed successfully.
.SH EXAMPLES
.PP
To synchronize the log directory for experiment "neptune/myexp" with the log
holes on the experimental nodes.
.PP
.RS
[vmars@users ~] loghole -e neptune/myexp sync
.RE
.PP
To archive the newly recovered logs and print out just the name of the new log
file:
.PP
.RS
[vmars@users ~] loghole -e neptune/myexp -q archive
.RE
.SH FILES
.TP
/proj/\fIpid\fR/exp/\fIeid\fR/logs
The log directory for an experiment.
.TP
/proj/\fIpid\fR/exp/\fIeid\fR/logs/\fInode
The log directory for a node in the experiment.
.TP
/proj/\fIpid\fR/exp/\fIeid\fR/logs/\fIlink
The log directory for a traced LAN or link.  The symbolic links in these
directories refer to the pcap(3) files for a node connected to this LAN or
link.
.TP
/proj/\fIpid\fR/exp/\fIeid\fR/logs/\fIlink\fR/__all.recv.0
The pcap(3) file that contains a merge of all the pre-shaped packets captured
by the link trace agents on this LAN or link.
.TP
/proj/\fIpid\fR/exp/\fIeid\fR/logs/\fIlink\fR/*.xpl
The output of "tcptrace -G" on the __all.recv.0 file.
.TP
/local/logs
One of the log directories on experimental nodes that is automatically sync'd.
Users should place any logs/data they want transferred back in this directory.
.TP
/var/emulab/logs
Another log directory on experimental nodes that is automatically sync'd.  This
directory usually holds logs generated by the Emulab software running on the
node.
.SH SEE ALSO
event-sched(8), tevc(1), zip(1), rsync(1), pcap(3), mergecap(1), tcptrace(1),
xplot(1)
.SH AUTHOR
The Emulab project at the University of Utah.
.SH NOTES
The Emulab project can be found on the web at
.IR http://www.emulab.net
