#!/usr/bin/perl -wT

my $ping	= "/sbin/ping";
my $TB		= "/usr/testbed/bin";
my $power	= "$TB/power";
my $me		= "root";
my $dbg		= 1;
my $net		= "fxp";
my $pipe	= 1;
my $DBOSID	= "FBSD40-STD";

# Need to make sure we use the right identity file in case we're
# setuid root and $ENV{HOME} is wrong
my $identity    = "-i /root/.ssh/identity";
my $rsh		= "sshtb $identity -q";
my $ssh		= "sshtb $identity -q";
my $rcp		= "scptb $identity -q";

# Scrub environment
$ENV{PATH} = "/usr/testbed/bin:/bin:/usr/bin:/usr/local/bin";
delete @ENV{qw(IFS CDPATH ENV BASH_ENV)};

# Apparently ssh checks to see if ruid != euid, and sets eduid=ruid
# if so. So, let's let it see what it wants...
if ($> == 0) {
	$< =0;
}

my %delaynodes  = ();
my %delaylinks  = ();
my %delayparams = ();

$| = 1; #Turn off line buffering on output

#
# Set up for querying the database.
# 
use Mysql;
my $DB = Mysql->connect("localhost", "tbdb", "script", "none");

if ( $#ARGV < 0) {
    die("Usage: delay_setup <ifc_file>\n". 	
	"Sets delay node configuration from a .ir file.\n");
}

#
# Must run, effectively, as root.
# 
if ($> != 0) {
    die("This won't work unless you run as user $me\n");
}

#
# Open up the ir file.
#
if (-e "$ARGV[0]" ) {
    open(IN,$ARGV[0]) || die("Couldn't open $ARGV[0]\n");
}

my $virtsection=0;

#
# Look for the start of the VIRTUAL section. Error if not found
#
while (<IN>) {
    if ( /^start virtual/i ) { 
	$virtsection=1; 
	print STDERR "Start VIRTUAL section...\n" if $dbg;
	last;
    }
}
if ($virtsection == 0) {
    die("No VIRTUAL section in $ARGV[0]\n");
}

#
# Okay, parse the VIRTUAL section.
# 
if ($virtsection == 1) {
    #
    # Search the NODES section for delayX labels and save the name of the
    # PC operating as the delay node (tbpcX).
    # 
    while (<IN>) {
	if ( /^start nodes/i ) { 
	    print STDERR "Start NODES section...\n" if $dbg;
	    next;
	}
	elsif ( /^end nodes/i ) {
	    print STDERR "End NODES section...\n" if $dbg;
	    last;
	}
	my ($node,$pc) = split();
	if ($node =~ /^delay/) {
	    print STDERR "$node $pc\n" if $dbg;

	    # We can safely untaint these variables
	    if (!($node =~ /^(\w+\d*)$/)) {
		die "Unexpected data in \$node : $node\n";
	    } else {
		$node = $1;
	    }
	    if (!($pc =~ /^(\w+\d*)$/)) {
		die "Unexpected data in \$pc : $pc\n";
	    } else {
		$pc = $1;
	    }

	    $delaynodes{$node} = $pc;
	}
    }

    #
    # Just record all the links for now. We will correlate them later.
    # 
    while (<IN>) {
	if ( /^start links/i ) { 
	    print STDERR "Start LINKS section...\n" if $dbg;
	    next;
	}
	elsif ( /^end links/i ) {
	    print STDERR "End LINKS section...\n" if $dbg;
	    last;
	}
	chop;
	#
	# Just record all the links for now.
	#
	my ($link,$rest) = split(' ', $_, 2);
	$delaylinks{$link} = [ split(' ', $rest) ];
    }
}

foreach my $link ( keys %delaylinks ) {
    my $rest = $delaylinks{$link};
    print STDERR "$link @{ $rest }\n" if $dbg;
}

#
# Skip to the end of the VIRTUAL section. Not really needed ...
# 
while (<IN>) {
    if ( /^end virtual/i ) { 
	$virtsection=0; 
	print STDERR "End VIRTUAL section...\n" if $dbg;
	last;
    }
}

#
# Now find the DELAY section.
#
while (<IN>) {
    if ( /^start delay/i ) { 
	print STDERR "Start DELAY section...\n" if $dbg;
	last;
    }
}

#
# Parse the DELAY section till it ends.
#
while (<IN>) {
    if ( /^end delay/i ) { 
	print STDERR "End DELAY section...\n" if $dbg;
	last;
    }

    chop;
    my ($link, $node, $bandw, $delay) = split();
    print STDERR "$link $node $bandw $delay\n" if $dbg;
    $delayparams{$link} = [ $node, $bandw, $delay ];
}

close(IN);

#
# First, check to make sure that each delay node is up and running the
# correct OS (FreeBSD). We get all the nodes rebooted at once, and then
# wait to start running the delay configuration setup stuff.
#
foreach my $link ( keys %delayparams ) {
    my $node  = $delayparams{$link}[0];
    my $pc    = $delaynodes{$node};


    #
    # database goo. We check to make sure the default image is set to
    # FreeBSD, and reset it if not. 
    #
    my $cmd = "select def_boot_image_id from nodes where node_id='$pc'";
    my $sth = $DB->query($cmd);
    my @row = $sth->fetchrow_array();
    print STDERR "$pc is currently set to OS = $row[0]\n" if $dbg;
    if ($row[0] ne $DBOSID) {
	print STDERR "Changing default OS for $pc to $DBOSID\n";
	$cmd = "update nodes set def_boot_image_id='$DBOSID' ";
	$cmd = "$cmd where node_id='$pc'";
	$sth = $DB->query($cmd);
	if ($sth == 0) {
	    die("Database update failed. Aborted...\n");
	}
    }

    #
    # See if the machine is pingable. If its not pingable, then
    # we just power cycle the machine rather than wait for a bunch
    # of ssh/rsh commands to time out.
    #
    print STDERR "Pinging $pc ... \n" if $dbg;
    if (-e $ping) {
	open(PING, "$ping -c 4 $pc 2>&1 |");
    }
    else {
	die("PING command $ping not found!\n");
    }
    do {
    }
    until ( <PING> =~ /transmitted, (\d*) packets received/ );
    close(PING);
    print STDERR "Got back $1 ping packets from $pc.\n" if $dbg;

    #
    # Power cycle if the machine is dead. It will come back up with the
    # proper OS, cause we modified the database above.
    #
    if ( $1 == 0 ) {
	print STDERR "$pc appears to be dead. Power cycling ... ";
	PowerCycle($pc);
	print STDERR "Done!\n";
    }

    #
    # Machine is up. See if its already running the proper OS so that we can
    # avoid a reboot.
    #
    open(UNAME, "$rsh $pc uname -a 2>&1 |");
    $_ = <UNAME>;
    close(UNAME);
    my $OS = "Unknown";    
    if ( $_ ) {
	@temp = split(" ",$_);
	$OS = $temp[0];
    }
    if ( $OS eq "FreeBSD" ) {
	print STDERR "$pc appears to be running the correct OS\n";
	next;
    }

    #
    # Time to reboot or power cycle. 
    # 
    print STDERR "Rebooting $pc cause its not running the correct OS\n";

    if (system("$rsh -l root $pc /sbin/reboot") == 0 ||
	system("$ssh -l root $pc /sbin/reboot") == 0) {
	printf STDERR "$pc appears to be rebooting\n" if $dbg;
    }
    else {
	print STDERR "$pc appears to be unrepsonsive Power cycling ... ";
	PowerCycle($pc);
	print STDERR "Done!\n";
    }
}

#
# Okay, got everything we need. Generate some script files 
#
foreach my $link ( keys %delayparams ) {
    my $node  = $delayparams{$link}[0];
    my $bandw = $delayparams{$link}[1];
    my $delay = $delayparams{$link}[2];
    my $pc    = $delaynodes{$node};
    my $cards = ();

    print STDERR "$link, $node, $pc, $bandw, $delay\n" if $dbg;

    foreach my $pclink ( @{ $delaylinks{$link} } ) {
	if ($pclink =~ /$pc/) {
	    $_ = $pclink;
	    s/$pc-/$net/g;
	    $pclink = $_;
	    push @cards, $pclink;
	}
    }
    my $iface1 = $cards[0];		# Okay, fxp0
    my $iface2 = $cards[1];		# Okay, fxp1
    my $fname  = "/tmp/delayconfig_${pc}_$$";
    
    open(TEMP, "> $fname");
    print TEMP "sysctl -w net.link.ether.bridge=0\n";
    print TEMP "sysctl -w net.link.ether.bridge_ipfw=0\n";
    print TEMP "sysctl -w net.link.ether.bridge_cfg=fxp4:6,";
    print TEMP "$iface1:69,$iface2:69,\n";
    print TEMP "sysctl -w net.link.ether.bridge=1\n";
    print TEMP "sysctl -w net.link.ether.bridge_ipfw=1\n";

    #
    # Try to form unqiue pipe numbers, since at some point I'll have
    # to deal with one node doing two delays,
    # 
    my $p1 = $pipe++;
    my $p2 = $pipe++;

    print TEMP "ipfw -f flush\n";
    print TEMP "ipfw add pipe $p1 ip from any to any in recv $iface1\n";
    print TEMP "ipfw add pipe $p2 ip from any to any in recv $iface2\n";
    print TEMP "ipfw pipe $p1 config delay ${delay}ms bw ${bandw}Mbit/s\n";
    print TEMP "ipfw pipe $p2 config delay ${delay}ms bw ${bandw}Mbit/s\n";
    print TEMP "echo \"Delay Configuration Complete\"\n";
    
    close(TEMP);

    if ($dbg) {
	system("cat $fname");
    }

    #
    # Copy the file over to the target machine. Since the machine might
    # have been rebooted above, run a short ping waiting for it come alive.
    # The most you want to wait is 60 seconds, I think, before throwing
    # in the towl.

    # Wait a few seconds to make sure the node has gone down for the reboot
    # already. Then start pinging it...
    #
    # Constant in here should be big enough for a reboot cmd to take effect,
    # but not so big that the node could have already come all the way back up

    sleep(10); 
    
    # Sigh, a 60 second ping results in the script waiting until all the
    # packets are sent from all the pings, before it will exit. So,
    # loop doing a bunch of shorter pings
    #
    print STDERR "Checking $pc to make sure it is alive ... " if $dbg;
    for ($i = 0; $i < 30; $i++) {
	open(PING, "$ping -c 2 $pc 2>&1 |");
	do {
	    $_ = <PING>;
	    if ( $_ =~ /bytes from/ ) {
		#
		# Do not close PING, cause we end up waiting for all the
		# packets to be sent.
		close(PING);
		print STDERR "Yep, alive and well\n" if $dbg;
		goto ALIVE;
	    }
	}
	until ( $_ =~ /transmitted, (\d*) packets received/ );
    }
    close(PING);
    die("$pc is not responding. Better check into it\n");
 ALIVE:

    #
    # Copy the file over to the target machine.
    #
    my $tries=0;
    my $max_tries=5;
    my $interval=5;
    while (system("$rcp $fname $pc:/etc/rc.delayconfig") && 
	   ($tries < $max_tries)) {
        $tries++;
        print STDERR "Remote Copy to $pc failed... Waiting and retrying...\n";
	# Sleep $interval seconds longer each time
	# Waits in total ($max_tries)! * $interval
	# seconds after its pingable before giving up
	sleep ($interval*$tries); 
    }
    if ($tries>=$max_tries) {
	die("Error copying delay config file to $pc\n");
    }
    unlink($fname);

    #
    # Now run the config script on the target. We look for the echo
    # at the end of the script that says it completed okay (See above).
    # The script generated above needs to be changed so that it terminates
    # early if one of the commands fails, but I have not done that yet.
    # 
    open(CONFIG, "$rsh $pc sh /etc/rc.delayconfig 2>&1 |");
    while ( $_ = <CONFIG> ) {
	if ( $_ =~ /Complete/ ) {
	    close(CONFIG);
	    goto FIGGED;
	}
    }
    die("Problem running configuration script on delay node $pc.\n");
FIGGED:
    print STDERR "Wow! Delay node $pc configured okay!\n" if $dbg;
}

print STDERR "Done!\n";

#
# Power cycle a PC using the testbed power program.
#
sub PowerCycle {
    local($pc) = @_;

    open(POWER, "$power cycle $pc 2>&1 |");
    $_ = <POWER>;
    close(POWER);
    if ( $_ =~ /Reboot/ ) {
	return;
    }
    else {
	die("Could not power cycle $pc! Quitting\n");
    }
}

