#!/usr/bin/perl

#
# This gets invoked from the Web interface. CD into the proper directory
# and do the tb stuff.
#
# usage: tbdoit <path to working directory> <nsfile>
#
my $tbdir = "/usr/testbed/bin/";

if (@ARGV != 2) {
    print STDOUT "Usage: tbdoit <working dir> <project> <file>\n";
    exit(-1);
}
my $workdir = $ARGV[0];
my $project = $ARGV[1];
my $nsfile  = $ARGV[2];
my $base    = "$nsfile";
$_ = $nsfile;
s/\.ns//g;
$base = $_;
my $irfile  = "$base.ir";
my $repfile = "$base.report";

#
# We run the TB stuff in the given directory.
#
if (! chdir($workdir)) {
    print STDOUT "Could not chdir to $workdir\n";
    exit(-1);
}

print STDOUT "Running tbprerun with arguments: $project $nsfile\n";
if (system("$tbdir/tbprerun $project $nsfile") == 0) {
    print STDOUT "tbprerun failed!\n";
    exit(-1);
}

print STDOUT "Running tbrun with arguments: $irfile\n";
if (system("$tbdir/tbrun $irfile") == 0) {
    print STDOUT "tbrun failed!\n";
    exit(-1);
}

print STDOUT "Running tbreport with arguments: $irfile -v >& $repfile\n";
if (system("$tbdir/tbreport -v $irfile >& $repfile") == 0) {
    print STDOUT "tbreport failed!\n";
    exit(-1);
}

print STDOUT "Setup Success\n";
exit 0;


