#!/usr/bin/perl

#
# This gets invoked from the Web interface. CD into the proper directory
# and do the tb stuff.
#
# usage: tbstopit <path to working directory> <irfile>
#
my $tbdir = "/usr/testbed/bin/";

if (@ARGV != 2) {
    print STDOUT "Usage: tbstopit <working dir> <irfile>\n";
    exit(-1);
}
my $workdir = $ARGV[0];
my $irfile  = $ARGV[1];

#
# We run the TB stuff in the given directory.
#
if (! chdir($workdir)) {
    print STDOUT "Could not chdir to $workdir\n";
    exit(-1);
}

print STDOUT "Running tbend with arguments: $irfile\n";
if (system("$tbdir/tbend $irfile") == 0) {
    print STDOUT "tbend failed!\n";
    exit(-1);
}

print STDOUT "Termination Success\n";
exit 0;


