#!/usr/bin/perl

#
# This gets invoked from the Web interface. CD into the proper directory
# and do the tb stuff.
#
# usage: tbstopit <path to working directory> <project> <eid> <irfile>
#
my $tbdir = "/usr/testbed/bin/";

if (@ARGV != 4) {
    print STDOUT "Usage: tbstopit <working dir> <project> <eid> <irfile>\n";
    exit(-1);
}
my $workdir = $ARGV[0];
my $project = $ARGV[1];
my $eid     = $ARGV[2];
my $irfile  = $ARGV[3];

#
# We run the TB stuff in the given directory.
#
if (! chdir($workdir)) {
    print STDOUT "Could not chdir to $workdir\n";
    exit(-1);
}

print STDOUT "Running tbend with arguments: $project $eid $irfile\n";
if (system("$tbdir/tbend $project $eid $irfile") != 0) {
    print STDOUT "tbend failed!\n";
    exit(-1);
}

print STDOUT "Running rmacct with argument: $eid\n";
if (system("$tbdir/rmacct $eid") != 0) {
    print STDOUT "rmacct failed!\n";
    exit(-1); 
}

print STDOUT "Termination Success\n";
exit 0;


