#!/usr/local/bin/perl -w
#########################################################################
# vsnmpit - A General Purpose Visual SNMP Tool                          #
# (specialized for the Intel 510T Switch and APC power controllers)     #
#                                                                       #
#      Author: Mac Newbold, Flux Research Group, University of Utah     #
# Last Change: May 23, 2000                                             #
#     Version: 1.11                                                     #
#                                                                       #
#########################################################################

use strict;
use Tk;

#GLOBAL VARs

my $snmpdef_u = "-u";
my $snmpdef_v = "";
my $snmpdef_b = "-b";
my $snmpdef_c = "+c";
my $snmp_u = $snmpdef_u;
my $snmp_v = $snmpdef_v;
my $snmp_b = $snmpdef_b;
my $snmp_c = $snmpdef_c;


#Color values

my $main_bg = 'slateblue';
my $main_abg = 'mediumslateblue';
my $main_fg = 'white';
my $main_afg = 'white';
my $dis_fg = 'gray';
my $btn_bg = 'darkslateblue';
my $btn_fg = 'white';
my $btn_abg = 'slateblue';
my $btn_afg = 'white';
my $btn_dfg = 'gray';
my $stat_bg = 'mediumslateblue';
my $stat_fg = 'white';

#Build the Widgets now

#set up main
my $main = MainWindow->new();
$main->title("vsnmpit - Visual SnmpIt!");
$main->configure(-bg => $main_bg );

#set up the frames
my $btn_bar = 
    $main->Frame(-relief=>'groove',-borderwidth=>3,-bg=>$btn_bg,
		 -fg=>$btn_fg,-width=>50
		 )->pack(-side=>'top',-fill=>'x');
my $area_frm = 
    $main->Frame(-relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
		 -fg=>$main_fg,-width=>50
		 )->pack(-side=>'top',-fill=>'both');
my $area = 
    $area_frm->Frame(-relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
		 -fg=>$main_fg,-width=>50
		 )->pack(-side=>'top',-fill=>'both');
my $stat_bar = 
    $main->Frame(-relief=>'ridge',-borderwidth=>3,-bg=>$stat_bg,
		 -fg=>$stat_bg,-width=>50
		 )->pack(-side=>'bottom',-expand=>"1",-fill=>'x');
my $status;

#set up the buttons
my $VLAN_btn =
    $btn_bar->Button(-relief=>'raised',-borderwidth=>2,-bg=>$btn_bg,
		     -activebackground=>$btn_abg,-fg=>$btn_fg,
		     -width=>9, -anchor=>'center',-text=>"VLAN Setup",
		     -activeforeground=>$btn_afg,
		     -command=> sub { &msg($status,""); &vlanSetup}
		     )->pack(-side=>'left',-padx=>'2',-pady=>'2');
my $port_btn =
    $btn_bar->Button(-relief=>'raised',-borderwidth=>2,-bg=>$btn_bg,
		     -activebackground=>$btn_abg,-fg=>$btn_fg,
		     -width=>8, -anchor=>'center',-text=>"Port Setup",
		     -activeforeground=>$btn_afg,
		     -command=> sub { &msg($status,""); &portSetup("Alpha")}
		     )->pack(-side=>'left',-padx=>'2',-pady=>'2');
my $stat_btn =
    $btn_bar->Button(-relief=>'raised',-borderwidth=>2,-bg=>$btn_bg,
		     -activebackground=>$btn_abg,-fg=>$btn_fg,
		     -width=>8, -anchor=>'center',-text=>"Statistics",
		     -activeforeground=>$btn_afg,
		     -command=> sub { &msg($status,""); &stats("Alpha")}
		     )->pack(-side=>'left',-padx=>'2',-pady=>'2');
my $opt_btn =
    $btn_bar->Button(-relief=>'raised',-borderwidth=>2,-bg=>$btn_bg,
		     -activebackground=>$btn_abg,-fg=>$btn_fg,
		     -width=>7, -anchor=>'center',-text=>"Options",
		     -activeforeground=>$btn_afg,
		     -command=> sub { &msg($status,""); &optSetup}
		     )->pack(-side=>'left',-padx=>'2',-pady=>'2');
my $exit_btn= 
    $btn_bar->Button(-relief=>'raised',-borderwidth=>2,-bg => $btn_bg,
		     -activebackground=>$btn_abg,-fg=>$btn_fg,
		     -width=>2,-anchor=>'center',-text=>'Exit', 
		     -activeforeground=>$btn_afg,
		     -command=>sub{$main->destroy}
		     )->pack(-side=>'left',-padx=>'2',-pady=>'2');

#set up the status bar
$status = 
    $stat_bar->Label(-bg=>$stat_bg,-fg=>$stat_fg,-anchor=>'nw',
		     -justify=>'left',-wraplength=>'550'
		     )->pack(-side=>'left',-expand=>"1",-fill=>'both');


&msg($status,"Welcome to vsnmpit - Visual SnmpIt!");


&MainLoop();

sub msg {
    (my $area, my @lines)=@_;
    my $text=join("",@lines);
    $area->configure(-text=>$text);
    $area->update();
}

#used in numerical sorts
sub num { $a <=> $b; }

#################################################################
#
# VLAN SETUP SECTION
#
#################################################################

sub vlanSetup {
    my $add_name = "";
    my @members =();
    my $name_field= "";
    my $memb_field= "";
    my $file_field= "";
    $area->pack('forget');
    $area = 
	$area_frm->Frame(-relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			 -fg=>$main_fg,-width=>50
			 )->pack(-side=>'top',-fill=>'both');
    my $titles =
	$area->Frame(-relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg
		     )->pack(-side=>'top',-expand=>"1",-fill=>'x');
    my $table =
	$area->Frame(-relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg
		     )->pack(-side=>'top',-expand=>"1",-fill=>'both');
    my $remove = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg,-text=>'Remove',-width=>8
		     )->pack(-side=>'left',-fill=>'x');
    my $number = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg,-text=>'VLAN #',-width=>8
		     )->pack(-side=>'left',-fill=>'x');
    my $name = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg,-text=>'VLAN Name',-width=>12
		     )->pack(-side=>'left',-fill=>'x');
    my $members = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg,-text=>'VLAN Members',-width=>16
		     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    my %names=();
    my %members=();
    my @line=();
    my $ID=0;
    open(DATA,"snmpit ".join(" ",@ARGV)." -l 2>&1 |");
    while (<DATA>) {
	chop;
	if (/^ID/) {next;}
	if (/^-----/) {next;}
	s/\t\t/\t/g;
	@line= split("\t",$_);
	$ID = shift(@line);
	$names{$ID}= shift(@line);
	$members{$ID}= join(" ",sort @line);
    }
    close (DATA);
    my %vlans = ();
    foreach $ID ( sort num keys(%names)) {
	my $row = 
	    $table->Frame(-relief=>'flat',
			 -bg=>$main_bg,-fg=>$main_fg
			 )->pack(-side=>'top',-expand=>"1",-fill=>'x');

#EDIT HERE IF SYSTEM VLAN CHANGES

	if ($ID != 1) {
	    $row->Checkbutton
		(-variable=>\$vlans{$ID},-relief=>'sunken',
		 -width=>5,-anchor=>'center',
		 -bg=>$main_bg,-fg=>$main_fg,
		 -activebackground=>$main_abg,
		 -activeforeground=>$main_afg,
		 -selectcolor=>$btn_bg,
		 -borderwidth=>3
		 )->pack(-side=>'left',-fill=>'y');
	} else {
	    $row->Label(-relief=>'sunken',
			-width=>8,-anchor=>'center',
			-bg=>$main_bg,-fg=>$main_fg,
			-borderwidth=>3
			)->pack(-side=>'left',-fill=>'y');
	}	    
	$row->Label(-relief=>'sunken',-text=>$ID,-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,
		    -borderwidth=>3
		    )->pack(-side=>'left',-fill=>'y');
	$row->Label(-relief=>'sunken',-text=>$names{$ID},-width=>12,
		    -bg=>$main_bg,-fg=>$main_fg,
		    -borderwidth=>3
		    )->pack(-side=>'left',-fill=>'y');
	$row->Label(-relief=>'sunken',-text=>$members{$ID},
		    -bg=>$main_bg,-fg=>$main_fg,-anchor=>'w',
		    -borderwidth=>3,-wraplength=>'350',-justify=>'left'
		     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    }
    my $row = 
	$table->Frame(-relief=>'flat',-borderwidth=>2,
		      -bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'top',-expand=>"1",-fill=>'x');
    my $remove_btn = 
	$row->Button(-text=>'Remove',-bg=>$main_bg,-width=>'5', 
		     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
		     -fg=>$main_fg,-activebackground=>$main_abg,
		     -activeforeground=>$main_afg,
		     -command=> sub { 
			 my @removeMe = ();
			 foreach $ID (sort num keys %vlans) {
			     if ($vlans{$ID}) {
				 push (@removeMe, $ID);
			     }
			 }
			 if (@removeMe) {
			     &msg($status,"Removing VLAN(s) ",
				  join(" ",@removeMe),
				  "\nThis should take about ",
				  ($snmp_u ne "-u" ? 10 : 20)," seconds...");
			     &removeVLANs(@removeMe);     
			     &vlanSetup;
			 }
		     }
		     )->pack(-side=>'left');
    my $add_btn = 
	$row->Button(-text=>'Add:',-bg=>$main_bg,-width=>'5', 
		     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
		     -fg=>$main_fg,-activebackground=>$main_abg,
		     -activeforeground=>$main_afg,
		     -command=> sub {     
			 $add_name = $name_field->get();
			 if (! $add_name) {
			     $add_name="";
			 }
			 my $memberentry = $memb_field->get();
			 $memberentry =~ s/,/ /g;
			 $memberentry =~ s/  / /g;
			 @members = split(' ',$memberentry);
			 if (@members) {
			     &msg($status,"Adding VLAN $add_name with ",
				  join(", ",@members),
				  "\nThis should take about ",
				  ($snmp_u ne "-u" ? 10 : 20)," seconds...");
			     &addVLAN($add_name,@members);     
			     &vlanSetup;} }
		     )->pack(-side=>'left');
    $name_field = 
	$row->Entry(-relief=>'sunken',-width=>12,
		    -bg=>$main_bg,-fg=>$main_fg,
		    -cursor=>['xterm',$main_fg,$main_bg],
		    -borderwidth=>3
		    )->pack(-side=>'left');
    $memb_field = 
	$row->Entry(-relief=>'sunken',
		    -bg=>$main_bg,-fg=>$main_fg,
		    -cursor=>['xterm',$main_fg,$main_bg],
		    -borderwidth=>3
		     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    $row = 
	$table->Frame(-relief=>'flat',-borderwidth=>2,
		      -bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'top',-expand=>"1",-fill=>'x');
    my $refresh =
	$row->Button(-text=>'Refresh',-bg=>$main_bg,-width=>'14', 
		     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
		     -fg=>$main_fg,-activebackground=>$main_abg,
		     -activeforeground=>$main_afg,
		     -command=> sub {     
			 &vlanSetup; }
		     )->pack(-side=>'left');
    my $file_btn = 
	$row->Button(-text=>'From File:',-bg=>$main_bg,-width=>'9', 
		     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
		     -fg=>$main_fg,-activebackground=>$main_abg,
		     -activeforeground=>$main_afg,
		     -command=> sub {     
			 my $file_name = $file_field->get();
			 if ($file_name) {
			     &msg($status,"Adding VLAN(s) from file $file_name",
				  "\nThis should take about ",
				  ($snmp_u ne "-u" ? 10 : 20)," seconds...");
			     &fileVLAN($file_name);     
			     &vlanSetup;} }
		     )->pack(-side=>'left');
    $file_field = 
	$row->Entry(-relief=>'sunken',
		    -bg=>$main_bg,-fg=>$main_fg,
		    -cursor=>['xterm',$main_fg,$main_bg],
		    -borderwidth=>3
		     )->pack(-side=>'left',-expand=>"1",-fill=>'x');


    $area->pack();
}

sub addVLAN {
    (my $name, my @v) = @_;
    if ($name) {
	open(DATA,"snmpit ".join(" ",@ARGV)." $snmp_u $snmp_v -m \"$name\" -vlan " . 
	     join(" ",@v)." 2>&1  |");
    } else {
	open(DATA,"snmpit ".join(" ",@ARGV)." $snmp_u $snmp_v -vlan ". join(" ",@v)." 2>&1  |");
    }
    my @output =();
    while (<DATA>) {
	chop;
	push(@output, $_);
    }
    close (DATA);
    if (join('',@output) =~ /Succeeded/i) {
	push(@output,"Switch VLAN table updated.");
    }
    &msg($status,join("\n",@output));
}

sub removeVLANs {
    (my @v) = @_;
    open(DATA,"snmpit ".join(" ",@ARGV)." $snmp_u $snmp_v -r ".join(" ",@v)." 2>&1  |");
    my @output =();
    while (<DATA>) {
	chop;
	push(@output, $_);
    }
    close (DATA);
    &msg($status,join("\n",@output));
}

sub fileVLAN {
    (my $file) = @_;
    open(DATA,"snmpit ".join(" ",@ARGV)." $snmp_u $snmp_v -f $file 2>&1  |");
    my @output =();
    while (<DATA>) {
	chop;
	push(@output, $_);
    }
    close (DATA);
    &msg($status,join("\n",@output));
}

#################################################################
#
# PORT SETUP SECTION
#
#################################################################

sub portSetup {
    my $switch="";
    my @args=();
    ($switch, @args) = @_;
    $area->pack('forget');
    $area = 
	$area_frm->Frame(-relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			 -fg=>$main_fg,-width=>50
			 )->pack(-side=>'top',-fill=>'both');
    my $buttons =
	$area->Frame(-relief=>'groove',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg
		     )->pack(-side=>'top',-expand=>"1",-fill=>'x');
    my $sw_btn1 = 
	$buttons->Button
	    (-text=>'Alpha',-bg=>$main_bg,-width=>'5', 
	     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
	     -fg=>$main_fg,-activebackground=>$main_abg,
	     -activeforeground=>$main_afg,
	     -command=> sub { &portSetup("Alpha"); }
	     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    my $sw_btn2 = 
	$buttons->Button
	    (-text=>'Beta',-bg=>$main_bg,-width=>'5', 
	     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
	     -fg=>$main_fg,-activebackground=>$main_abg,
	     -activeforeground=>$main_afg,
	     -command=> sub { &portSetup("Beta"); } 
	     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    my $sw_btn3 = 
	$buttons->Button
	    (-text=>'Gamma',-bg=>$main_bg,-width=>'5', 
	     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
	     -fg=>$main_fg,-activebackground=>$main_abg,
	     -activeforeground=>$main_afg,
	     -command=> sub { &portSetup("Gamma"); }
	     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    my $sw_btn4 = 
	$buttons->Button
	    (-text=>'Delta',-bg=>$main_bg,-width=>'5', 
	     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
	     -fg=>$main_fg,-activebackground=>$main_abg,
	     -activeforeground=>$main_afg,
	     -command=> sub { &portSetup("Delta"); } 
	     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    
    my $sw_name="";
    my $sw_IP="";
    my %names=();
    my %vlanName=();
    my %enabled=();
    my %link=();
    my %auto=();
    my %spd=();
    my %dup=();
    my @line=();
    my $port=0;
    open(DATA,"snmpit ".join(" ",@ARGV)." -i $switch -s 2>&1 |");
    while (<DATA>) {
	chop;
	if (/^Port Configuration, Testbed Switch (.*) \((.*)\)/) {
	    $sw_name = $1;
	    $sw_IP = $2;
	    next;
	}
	if (/^Port Interface/) {next;}
	if (/^--/) {next;}
	s/^ +//;
	s/ +/\t/;
	s/\t\t\t/\t\t/;
	s/Mbit\t\t/Mbit\t/;
	@line= split("\t",$_);
	$port = shift(@line);
	$names{$port}= shift(@line);
	$vlanName{$port}= shift(@line);
	$enabled{$port}= shift(@line);
	$link{$port}= shift(@line);
	$auto{$port}= shift(@line);
	$spd{$port}= shift(@line);
	$dup{$port}= shift(@line);
    }
    close (DATA);
    
    my $titlebar =
	$area->Frame(-relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg
		     )->pack(-side=>'top',-expand=>"1",-fill=>'x');
    my $titles =
	$area->Frame(-relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg
		     )->pack(-side=>'top',-expand=>"1",-fill=>'x');
    my $table =
	$area->Frame(-relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg
		     )->pack(-side=>'top',-expand=>"1",-fill=>'both');
    my $switch_title =
	$titlebar->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
			 -fg=>$main_fg,
			 -text=>"Port Configuration - Testbed Switch ".
			 "$sw_name ($sw_IP)"
			 )->pack(-side=>'left',-expand=>1,-fill=>'x');
    
    my $marks = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'Select',-width=>6
		       )->pack(-side=>'left',-fill=>'x');
    my $L_portNum = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'Port #',-width=>6
		       )->pack(-side=>'left',-fill=>'x');
    my $L_interface = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'Interface',-width=>10
		       )->pack(-side=>'left',-expand=>1,-fill=>'x');
    my $L_vlan = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'VLAN',-width=>8
		       )->pack(-side=>'left',-expand=>1,-fill=>'x');
    my $L_enabled = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'Enabled',-width=>8
		       )->pack(-side=>'left',-fill=>'x');
    my $L_link = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'Link',-width=>6
		       )->pack(-side=>'left',-fill=>'x');
    my $L_autoConf = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'Auto Config.',-width=>12
		       )->pack(-side=>'left',-fill=>'x');
    my $L_speed = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'Speed',-width=>14
		       )->pack(-side=>'left',-fill=>'x');
    my $L_duplex = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'Duplex',-width=>10
		       )->pack(-side=>'left',-fill=>'x');
    my %marked=();
    my $selVLANs=0;
    foreach $port ( sort num keys(%names)) {
	my $row = 
	    $table->Frame(-relief=>'flat',
			  -bg=>$main_bg,-fg=>$main_fg
			  )->pack(-side=>'top',-expand=>"1",-fill=>'x');
	$row->Checkbutton(-variable=>\$marked{$port},-relief=>'sunken',
			  -width=>3,-anchor=>'center',
			  -bg=>$main_bg,-fg=>$main_fg,
			  -activebackground=>$main_abg,
			  -activeforeground=>$main_afg,
			  -selectcolor=>$btn_bg,-borderwidth=>3,
			  -command => sub {
			      if ($selVLANs) {
				  my $myVlan=$vlanName{$port};
				  foreach my $p (keys %names) {
				      if ($vlanName{$p} eq $myVlan) {
					  $marked{$p}=$marked{$port};
				      }
				  }
			      }
			  }
			  )->pack(-side=>'left');
	$row->Label(-relief=>'sunken',-text=>$port,-width=>6,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left');
	$row->Label(-relief=>'sunken',-text=>$names{$port},-width=>10,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-expand=>1,-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$vlanName{$port},-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-expand=>1,-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$enabled{$port},-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left');
	$row->Label(-relief=>'sunken',-text=>$link{$port},-width=>6,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left');
	$row->Label(-relief=>'sunken',-text=>$auto{$port},-width=>12,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left');
	$row->Label(-relief=>'sunken',-text=>$spd{$port},-width=>14,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left');
	$row->Label(-relief=>'sunken',-text=>$dup{$port},-width=>10,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left');
    }
    my $row = 
	$table->Frame(-relief=>'flat',-borderwidth=>2,
		      -bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'top',-expand=>"1",-fill=>'both');
    my $btn_frm = 
	$row->Frame(-relief=>'flat',-borderwidth=>2,
		      -bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'left',-expand=>"1",-fill=>'both');
    my $sel_mode_frm = 
	$btn_frm->Frame(-relief=>'flat',-borderwidth=>2,
		      -bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'top',-expand=>"1",-fill=>'both');
    my $byPort_opt = 
	$sel_mode_frm->Radiobutton(-variable=>\$selVLANs,-value=>"0",
			     -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			     -fg=>$main_fg,-activebackground=>$main_abg,
			     -activeforeground=>$main_afg,-anchor=>'nw',
			     -selectcolor=>$btn_bg,-width=>'11',
			     -text=>"Sel. by Port"
			     )->pack(-side=>'left',-fill=>'x',-padx=>'2');
    my $byVLAN_opt = 
	$sel_mode_frm->Radiobutton(-variable=>\$selVLANs,-value=>"1",
			     -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			     -fg=>$main_fg,-activebackground=>$main_abg,
			     -activeforeground=>$main_afg,-anchor=>'nw',
			     -selectcolor=>$btn_bg,-width=>'11',
			     -text=>"Sel. by VLAN"
			     )->pack(-side=>'left',-fill=>'x',-padx=>'2');
    my $sel_frm = 
	$btn_frm->Frame(-relief=>'flat',-borderwidth=>2,
		      -bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'top',-expand=>"1",-fill=>'both');
    my $sel_all_btn = 
	$sel_frm->Button(-text=>'Select All',-bg=>$main_bg,-width=>'8', 
			 -anchor=>'center', -relief=>'raised',-borderwidth=>3,
			 -fg=>$main_fg,-activebackground=>$main_abg,
			 -activeforeground=>$main_afg,
			 -command=> sub { 
			     foreach $port ( sort num keys(%names)) {
				 $marked{$port}=1;
			     }
			 }
			 )->pack(-side=>'left',-expand=>1,-fill=>'both');
    my $desel_all_btn = 
	$sel_frm->Button(-text=>'Deselect All',-bg=>$main_bg,-width=>'8', 
			 -anchor=>'center', -relief=>'raised',-borderwidth=>3,
			 -fg=>$main_fg,-activebackground=>$main_abg,
			 -activeforeground=>$main_afg,
			 -command=> sub { 
			     foreach $port ( sort num keys(%names)) {
				 $marked{$port}=0;
			     }
			 }
			 )->pack(-side=>'left',-expand=>1,-fill=>'both');

    my $p_enable = "";
    my $p_auto = "";
    my $p_spd = "";
    my $p_dup = "";

    my $upd_frm = 
	$btn_frm->Frame(-relief=>'flat',-borderwidth=>2,
		      -bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'top',-expand=>"1",-fill=>'both');
    my $update_btn = 
	$upd_frm->Button(-text=>'Update',-bg=>$main_bg,-width=>'16', 
			 -anchor=>'center', -relief=>'raised',-borderwidth=>3,
			 -fg=>$main_fg,-activebackground=>$main_abg,
			 -activeforeground=>$main_afg,
			 -command=> sub { 
			     my @updateMe = ();
			     foreach $port (sort num keys %names) {
				 if ($marked{$port}) {
				     push (@updateMe, $port);
				 }
			     }
			     if (@updateMe) {
				 &msg($status,"Updating Port(s) ",
				      join(" ",@updateMe),
				      "\nThis should take about ",
				      ($#updateMe<12 ? 10:25)," seconds...");
				 &updatePorts($sw_IP,$p_enable,$p_auto,
					      $p_spd,$p_dup,@updateMe);
				 sleep(2);
				 &portSetup($switch);
			     }
			 }
			 )->pack(-side=>'top',-expand=>1,-fill=>'both');
    my $en_frm = 
	$row->Frame(-relief=>'flat',-borderwidth=>2,-bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'left',-fill=>'y');
    my $auto_frm = 
	$row->Frame(-relief=>'flat',-borderwidth=>2,-bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'left',-fill=>'y');
    my $spd_frm = 
	$row->Frame(-relief=>'flat',-borderwidth=>2,-bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'left',-fill=>'y');
    my $dup_frm = 
	$row->Frame(-relief=>'flat',-borderwidth=>2,-bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'left',-fill=>'y');
    my $en_opt = 
	$en_frm->Radiobutton(-variable=>\$p_enable,-value=>"-e",
			     -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			     -fg=>$main_fg,-activebackground=>$main_abg,
			     -activeforeground=>$main_afg,-anchor=>'nw',
			     -selectcolor=>$btn_bg,-width=>'9',
			     -text=>"Enable"
			     )->pack(-side=>'top',-fill=>'x',
				     -padx=>'3',-pady=>'3');
    my $dis_opt = 
	$en_frm->Radiobutton(-variable=>\$p_enable,-value=>"-d",
			     -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			     -fg=>$main_fg,-activebackground=>$main_abg,
			     -activeforeground=>$main_afg,-anchor=>'nw',
			     -selectcolor=>$btn_bg,-width=>'9',
			     -text=>"Disable"
			     )->pack(-side=>'top',-fill=>'x',
				     -padx=>'3',-pady=>'3');
    my $en_no_opt = 
	$en_frm->Radiobutton(-variable=>\$p_enable,-value=>"",
			     -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			     -fg=>$main_fg,-activebackground=>$main_abg,
			     -activeforeground=>$main_afg,-anchor=>'nw',
			     -selectcolor=>$btn_bg,-width=>'9',
			     -text=>"No Change"
			     )->pack(-side=>'top',-fill=>'x',
				     -padx=>'3',-pady=>'3');
    my $spd100_opt = "";
    my $spd10_opt = "";
    my $spd_no_opt = "";
    my $dupFull_opt = "";
    my $dupHalf_opt = "";
    my $dup_no_opt = "";

    my $auto_on_opt = 
	$auto_frm->
	    Radiobutton(-variable=>\$p_auto,-value=>"+a",
			-relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			-fg=>$main_fg,-activebackground=>$main_abg,
			-activeforeground=>$main_afg,-anchor=>'nw',
			-selectcolor=>$btn_bg,-width=>'11',
			-text=>"AutoConf On", -command => sub {
			    $spd100_opt->configure(-state=>'disabled');
			    $spd10_opt->configure(-state=>'disabled');
			    $spd_no_opt->configure(-state=>'disabled');
			    $dupFull_opt->configure(-state=>'disabled');
			    $dupHalf_opt->configure(-state=>'disabled');
			    $dup_no_opt->configure(-state=>'disabled');
			    $p_spd = "";
			    $p_dup = "";
			}
			)->pack(-side=>'top',-fill=>'x',
				-padx=>'3',-pady=>'3');
    my $auto_off_opt = 
	$auto_frm->
	    Radiobutton(-variable=>\$p_auto,-value=>"-a",
			-relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			-fg=>$main_fg,-activebackground=>$main_abg,
			-activeforeground=>$main_afg,-anchor=>'nw',
			-selectcolor=>$btn_bg,-width=>'11',
			-text=>"AutoConf Off", -command => sub {
			    $spd100_opt->configure(-state=>'normal');
			    $spd10_opt->configure(-state=>'normal');
			    $spd_no_opt->configure(-state=>'normal');
			    $dupFull_opt->configure(-state=>'normal');
			    $dupHalf_opt->configure(-state=>'normal');
			    $dup_no_opt->configure(-state=>'normal');
			}
			)->pack(-side=>'top',-fill=>'x',
				-padx=>'3',-pady=>'3');
    my $auto_opt = 
	$auto_frm->
	    Radiobutton(-variable=>\$p_auto,-value=>"",
			-relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			-fg=>$main_fg,-activebackground=>$main_abg,
			-activeforeground=>$main_afg,-anchor=>'nw',
			-selectcolor=>$btn_bg,-width=>'11',
			-text=>"No Change", -command => sub {
			    $spd100_opt->configure(-state=>'normal');
			    $spd10_opt->configure(-state=>'normal');
			    $spd_no_opt->configure(-state=>'normal');
			    $dupFull_opt->configure(-state=>'normal');
			    $dupHalf_opt->configure(-state=>'normal');
			    $dup_no_opt->configure(-state=>'normal');
			}			
			)->pack(-side=>'top',,-fill=>'x',
				-padx=>'3',-pady=>'3');
    $spd100_opt = 
	$spd_frm->Radiobutton(-variable=>\$p_spd,-value=>"-spd 100",
			      -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			      -fg=>$main_fg,-activebackground=>$main_abg,
			      -activeforeground=>$main_afg,-anchor=>'nw',
			      -disabledforeground=>$dis_fg,
			      -selectcolor=>$btn_bg,-width=>'9',
			      -text=>"100 Mbps"
			      )->pack(-side=>'top',-fill=>'x',
				      -padx=>'3',-pady=>'3');
    $spd10_opt = 
	$spd_frm->Radiobutton(-variable=>\$p_spd,-value=>"-spd 10",
			      -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			      -fg=>$main_fg,-activebackground=>$main_abg,
			      -activeforeground=>$main_afg,-anchor=>'nw',
			      -disabledforeground=>$dis_fg,
			      -selectcolor=>$btn_bg,-width=>'9',
			      -text=>"10 Mbps"
			      )->pack(-side=>'top',-fill=>'x',
				      -padx=>'3',-pady=>'3');
    $spd_no_opt = 
	$spd_frm->Radiobutton(-variable=>\$p_spd,-value=>"",
			      -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			      -fg=>$main_fg,-activebackground=>$main_abg,
			      -activeforeground=>$main_afg,-anchor=>'nw',
			      -disabledforeground=>$dis_fg,
			      -selectcolor=>$btn_bg,-width=>'9',
			      -text=>"No Change"
			      )->pack(-side=>'top',-fill=>'x',
				      -padx=>'3',-pady=>'3');
    $dupFull_opt = 
	$dup_frm->Radiobutton(-variable=>\$p_dup,-value=>"-dup Full",
			      -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			      -fg=>$main_fg,-activebackground=>$main_abg,
			      -activeforeground=>$main_afg,-anchor=>'nw',
			      -disabledforeground=>$dis_fg,
			      -selectcolor=>$btn_bg,-width=>'10',
			      -text=>"Full Duplex"
			      )->pack(-side=>'top',-fill=>'x',
				      -padx=>'3',-pady=>'3');
    $dupHalf_opt = 
	$dup_frm->Radiobutton(-variable=>\$p_dup,-value=>"-dup Half",
			      -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			      -fg=>$main_fg,-activebackground=>$main_abg,
			      -activeforeground=>$main_afg,-anchor=>'nw',
			      -disabledforeground=>$dis_fg,
			      -selectcolor=>$btn_bg,-width=>'10',
			      -text=>"Half Duplex"
			      )->pack(-side=>'top',-fill=>'x',
				      -padx=>'3',-pady=>'3');
    $dup_no_opt = 
	$dup_frm->Radiobutton(-variable=>\$p_dup,-value=>"",
			      -relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			      -fg=>$main_fg,-activebackground=>$main_abg,
			      -activeforeground=>$main_afg,-anchor=>'nw',
			      -disabledforeground=>$dis_fg,
			      -selectcolor=>$btn_bg,-width=>'10',
			      -text=>"No Change"
			      )->pack(-side=>'top',-fill=>'x',
				      -padx=>'3',-pady=>'3');
    $area->pack();
}

sub updatePorts {
    (my $switch, my $en, my $auto, my $spd, my $dup, my @ports) = @_;
    open(DATA,"snmpit ".join(" ",@ARGV)." -i $switch $snmp_v $snmp_b $snmp_c -p ".
	 join(" ",@ports)." $en $auto $spd $dup 2>&1  |");
    #print "snmpit -i $switch $snmp_v $snmp_b $snmp_c -p ".
    #	join(" ",@ports)." $en $auto $spd $dup ";
    my @output =();
    while (<DATA>) {
	chop;
	push(@output, $_);
    }
    close (DATA);
    push(@output,"Port Configurations updated.");
    &msg($status,join("\n",@output));
}


#################################################################
#
# STATS SECTION
#
#################################################################

sub stats {
    my $switch="";
    my @args=();
    ($switch, @args) = @_;
    $area->pack('forget');
    $area = 
	$area_frm->Frame(-relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			 -fg=>$main_fg,-width=>50
			 )->pack(-side=>'top',-fill=>'both');
    my $buttons =
	$area->Frame(-relief=>'groove',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg
		     )->pack(-side=>'top',-expand=>"1",-fill=>'x');
    my $sw_btn1 = 
	$buttons->Button
	    (-text=>'Alpha',-bg=>$main_bg,-width=>'5', 
	     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
	     -fg=>$main_fg,-activebackground=>$main_abg,
	     -activeforeground=>$main_afg,
	     -command=> sub { &stats("Alpha"); }
	     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    my $sw_btn2 = 
	$buttons->Button
	    (-text=>'Beta',-bg=>$main_bg,-width=>'5', 
	     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
	     -fg=>$main_fg,-activebackground=>$main_abg,
	     -activeforeground=>$main_afg,
	     -command=> sub { &stats("Beta"); } 
	     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    my $sw_btn3 = 
	$buttons->Button
	    (-text=>'Gamma',-bg=>$main_bg,-width=>'5', 
	     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
	     -fg=>$main_fg,-activebackground=>$main_abg,
	     -activeforeground=>$main_afg,
	     -command=> sub { &stats("Gamma"); }
	     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    my $sw_btn4 = 
	$buttons->Button
	    (-text=>'Delta',-bg=>$main_bg,-width=>'5', 
	     -anchor=>'center', -relief=>'raised',-borderwidth=>3,
	     -fg=>$main_fg,-activebackground=>$main_abg,
	     -activeforeground=>$main_afg,
	     -command=> sub { &stats("Delta"); } 
	     )->pack(-side=>'left',-expand=>"1",-fill=>'x');
    
    my $sw_name="";
    my $sw_IP="";
    my %names=();
    my %in1=();
    my %in2=();
    my %in3=();
    my %in4=();
    my %in5=();
    my %in6=();
    my %out1=();
    my %out2=();
    my %out3=();
    my %out4=();
    my %out5=();
    my %out6=();
    my @line=();
    my $port=0;
    open(DATA,"snmpit ".join(" ",@ARGV)." -i $switch -g 2>&1 |");
    while (<DATA>) {
	chop;
	if (/^Port Statistics, Testbed Switch (.*) \((.*)\)/) {
	    $sw_name = $1;
	    $sw_IP = $2;
	    next;
	}
	if (/InUcast/) {next;}
	if (/^Port Interface/) {next;}
	if (/^--/) {next;}
	s/^ +//;
	s/ +/\t/g;
	#s/\t\t\t/\t\t/;
	#s/Mbit\t\t/Mbit\t/;
	@line= split("\t",$_);
	$port = shift(@line);
	$names{$port}= shift(@line);
	$in1{$port}=shift(@line);
	$in2{$port}=shift(@line);
	$in3{$port}=shift(@line);
	$in4{$port}=shift(@line);
	$in5{$port}=shift(@line);
	$in6{$port}=shift(@line);
	$out1{$port}=shift(@line);
	$out2{$port}=shift(@line);
	$out3{$port}=shift(@line);
	$out4{$port}=shift(@line);
	$out5{$port}=shift(@line);
	$out6{$port}=shift(@line);
    }
    close (DATA);
    
    my $titlebar =
	$area->Frame(-relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg
		     )->pack(-side=>'top',-expand=>"1",-fill=>'x');
    my $titles =
	$area->Frame(-relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg
		     )->pack(-side=>'top',-expand=>"1",-fill=>'x');
    my $table =
	$area->Frame(-relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
		     -fg=>$main_fg
		     )->pack(-side=>'top',-expand=>"1",-fill=>'both');
    my $switch_title =
	$titlebar->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
			 -fg=>$main_fg,
			 -text=>"Port Statistics - Testbed Switch ".
			 "$sw_name ($sw_IP)"
			 )->pack(-side=>'left',-expand=>1,-fill=>'x');
    
    my $L_portNum = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'Port #',-width=>6
		       )->pack(-side=>'left',-fill=>"both");
    my $L_interface = 
	$titles->Label(-relief=>'sunken',-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>'Interface',-width=>10
		       )->pack(-side=>'left',-expand=>1,-fill=>"both");
    my $L_in1 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"In Octets",-width=>12
		       )->pack(-side=>"left",-fill=>"both");
    my $L_in2 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"In Unicast\nPackets",-width=>10
		       )->pack(-side=>"left",-fill=>"both");
    my $L_in3 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"In Non-\nUnicast\nPackets",
		       -width=>8
		       )->pack(-side=>"left",-fill=>"both");
    my $L_in4 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"In\nDiscards",-width=>8
		       )->pack(-side=>"left",-fill=>"both");
    my $L_in5 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"In\nErrors",-width=>8
		       )->pack(-side=>"left",-fill=>"both");
    my $L_in6 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"In\nUnknown\nProtocol",-width=>8
		       )->pack(-side=>"left",-fill=>"both");
    my $L_out1 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"Out Octets",-width=>12
		       )->pack(-side=>"left",-fill=>"both");
    my $L_out2 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"Out Unicast\nPackets",-width=>10
		       )->pack(-side=>"left",-fill=>"both");
    my $L_out3 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"Out Non-\nUnicast\nPackets",
		       -width=>8
		       )->pack(-side=>"left",-fill=>"both");
    my $L_out4 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"Out\nDiscards",-width=>8
		       )->pack(-side=>"left",-fill=>"both");
    my $L_out5 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"Out\nErrors",-width=>8
		       )->pack(-side=>"left",-fill=>"both");
    my $L_out6 = 
	$titles->Label(-relief=>"sunken",-borderwidth=>3,-bg=>$main_bg,
		       -fg=>$main_fg,-text=>"Out\nQueue\nLength",-width=>8
		       )->pack(-side=>"left",-fill=>"both");
    foreach $port ( sort num keys(%names)) {
	my $row = 
	    $table->Frame(-relief=>'flat',
			  -bg=>$main_bg,-fg=>$main_fg
			  )->pack(-side=>'top',-expand=>"1",-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$port,-width=>6,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left');
	$row->Label(-relief=>'sunken',-text=>$names{$port},-width=>10,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-expand=>1,-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$in1{$port},-width=>12,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$in2{$port},-width=>10,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$in3{$port},-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$in4{$port},-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$in5{$port},-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$in6{$port},-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$out1{$port},-width=>12,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$out2{$port},-width=>10,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$out3{$port},-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$out4{$port},-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$out5{$port},-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
	$row->Label(-relief=>'sunken',-text=>$out6{$port},-width=>8,
		    -bg=>$main_bg,-fg=>$main_fg,-borderwidth=>3
		    )->pack(-side=>'left',-fill=>'x');
    }
    my $row = 
	$table->Frame(-relief=>'flat',-borderwidth=>2,
		      -bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'top',-expand=>"1",-fill=>'both');
    my $btn_frm = 
	$row->Frame(-relief=>'flat',-borderwidth=>2,
		      -bg=>$main_bg,-fg=>$main_fg
		      )->pack(-side=>'left',-expand=>"1",-fill=>'both');
    my $refresh =
	$btn_frm->Button(-text=>'Refresh',-bg=>$main_bg,-width=>'14', 
		     -relief=>'raised',-borderwidth=>3,
		     -fg=>$main_fg,-activebackground=>$main_abg,
		     -activeforeground=>$main_afg,
		     -command=> sub { &stats($switch); }
		     )->pack(-side=>'left',-expand=>"1",-fill=>'both');
    
}


#################################################################
#
# OPTIONS SETUP SECTION
#
#################################################################

sub optSetup {
    $area->packForget();
    $area = 
	$area_frm->Frame(-relief=>'flat',-borderwidth=>3,-bg=>$main_bg,
			 -fg=>$main_fg,-width=>50
			 )->pack(-side=>'top',-fill=>'both');
    my $u_frm =
	$area->Frame(-bg=>$main_bg,-fg=>$main_fg,-relief=>'ridge'
		     )->pack(-side=>'top',-fill=>'x');
    my $u_opt = 
	$u_frm->Checkbutton(-variable=>\$snmp_u,-onvalue=>"-u",-offvalue=>"",
			    -relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
			    -fg=>$main_fg,-activebackground=>$main_abg,
			    -activeforeground=>$main_afg,-anchor=>'nw',
			    -selectcolor=>$btn_bg,-width=>'15',
			    -text=>"Wait for Update"
			    )->pack(-side=>'left',-fill=>'x',
				    -padx=>'5',-pady=>'3');
    my $u_desc =
	$u_frm->Label(-bg=>$main_bg,-fg=>$main_fg,-relief=>'sunken', 
		      -justify=>'left',-text=>
		      "Refreshes VLAN Table after switch has updated.\n"
		      ."Adds 10 seconds to VLAN reconfiguration time.\n"
		      ."When off, VLAN display will refresh, but changes\n"
		      ."won't be shown until the next refresh after 10\n"
		      ."seconds have passed. Only affects VLAN setup."
		      )->pack(-side=>'left',-fill=>'x',-expand=>"1",
			      -padx=>'5',-pady=>'3');
    my $v_frm =
	$area->Frame(-bg=>$main_bg,-fg=>$main_fg,-relief=>'ridge'
		     )->pack(-side=>'top',-fill=>'x');
    my $v_opt = 
	$v_frm->Checkbutton(-variable=>\$snmp_v,-onvalue=>"-v",-offvalue=>"",
			    -relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
			    -fg=>$main_fg,-activebackground=>$main_abg,
			    -activeforeground=>$main_afg,-anchor=>'nw',
			    -selectcolor=>$btn_bg,-width=>'15',
			    -text=>"Verbose Mode"
			    )->pack(-side=>'left',-fill=>'x',
				    -padx=>'5',-pady=>'3');
    my $v_desc =
	$v_frm->Label(-bg=>$main_bg,-fg=>$main_fg,-relief=>'sunken', 
		      -justify=>'left',-text=>
		      "Adds copius amounts of verbosity and debugging\n"
		      ."information to what gets output in the status bar."
		      )->pack(-side=>'left',-fill=>'x',-expand=>"1",
			      -padx=>'5',-pady=>'3');
    my $b_frm =
	$area->Frame(-bg=>$main_bg,-fg=>$main_fg,-relief=>'ridge'
		     )->pack(-side=>'top',-fill=>'x');
    my $b_opt = 
	$b_frm->Checkbutton(-variable=>\$snmp_b,-onvalue=>"+b",-offvalue=>"-b",
			    -relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
			    -fg=>$main_fg,-activebackground=>$main_abg,
			    -activeforeground=>$main_afg,-anchor=>'nw',
			    -selectcolor=>$btn_bg,-width=>'15',
			    -text=>"Blocking Mode"
			    )->pack(-side=>'left',-fill=>'x',
				    -padx=>'5',-pady=>'3');
    my $b_desc =
	$b_frm->Label(-bg=>$main_bg,-fg=>$main_fg,-relief=>'sunken', 
		      -justify=>'left',-text=>
		      "Waits for reply from switch before adding any new\n"
		      ."requests to the switch's instruction queue. Only\n"
		      ."affects port setup."
		      )->pack(-side=>'left',-fill=>'x',-expand=>"1",
			      -padx=>'5',-pady=>'3');
    my $c_frm =
	$area->Frame(-bg=>$main_bg,-fg=>$main_fg,-relief=>'ridge'
		     )->pack(-side=>'top',-fill=>'x');
    my $c_opt = 
	$c_frm->Checkbutton(-variable=>\$snmp_c,-onvalue=>"+c",-offvalue=>"-c",
			    -relief=>'raised',-borderwidth=>3,-bg=>$main_bg,
			    -fg=>$main_fg,-activebackground=>$main_abg,
			    -activeforeground=>$main_afg,-anchor=>'nw',
			    -selectcolor=>$btn_bg,-width=>'15',
			    -text=>"Confirm Changes"
			    )->pack(-side=>'left',-fill=>'x',
				    -padx=>'5',-pady=>'3');
    my $c_desc =
	$c_frm->Label(-bg=>$main_bg,-fg=>$main_fg,-relief=>'sunken', 
		      -justify=>'left',-text=>
		      "Most useful when Blocking is off. Verifies all port\n"
		      ."configuration changes after all requests have been\n"
		      ."sent. Only affects port setup."
		      )->pack(-side=>'left',-fill=>'x',-expand=>"1",
			      -padx=>'5',-pady=>'3');
    my $reset = 
	$area->Button(-text=>'Reset to Default Values',-bg=>$main_bg,
		      -anchor=>'center', -relief=>'raised',
		      -fg=>$main_fg,-activebackground=>$main_abg,
		      -activeforeground=>$main_afg,
		      -command=> sub {     
			  $snmp_u = $snmpdef_u;
			  $snmp_v = $snmpdef_v;
			  $snmp_b = $snmpdef_b;
			  $snmp_c = $snmpdef_c;
		      }
		      )->pack(-side=>'top',-expand=>'1',-fill=>'x',
			      -padx=>'5',-pady=>'3');

    $area->pack();
}
