#!/usr/bin/perl -w

# I can visualize topologies again, topper!

%color = (
  "pc850", "skyblue",
  "pc600", "steelblue",
  "pc",    "steelblue",
  "shark", "darkblue",
  "lan",   "green",
  "delay", "orange"
	  );

print "graph G {\n";
while (<>) {
    if (/^node/) {
	my ($nodename, $nodetype) = /^node\s+(\S+)\s+(\S+)/;
	$nodename =~ s/[^\w]/_/g;
	print "{node [label = $nodename, shape = box,";

	if (exists $color{ $nodetype }) {
	    print "color = " . $color{ $nodetype };
	} else {
	    warn "Warning! Unknown color for \"$nodetype\"--using default.\n";
	    print "color = skyblue";
	}
	print "] $nodename}\n";
    } elsif (/^link/) {
	my ($lhs, $rhs) = /^link\s+\S+\s+(\S+)\s+(\S+)/;
	$rhs =~ s/[^\w]/_/g;
	$lhs =~ s/[^\w]/_/g;
	print "$lhs -- $rhs;\n";
    }
}
print "}\n";
