#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2003 University of Utah and the Flux Group.
# All rights reserved.
#

if [ x"$new_host_name" != x ]; then
    echo "Setting hostname to $new_host_name"
    echo ${new_host_name}.emulab.net > /etc/myname
    hostname `cat /etc/myname`
fi

exit 0
