#!/bin/sh
#
# EMULAB-COPYRIGHT
# Copyright (c) 2000-2002 University of Utah and the Flux Group.
# All rights reserved.
#
. /etc/emulab/paths.sh

if [ -x $BINDIR/cpuspeed.awk ]; then
	cpuspeed=`$BINDIR/cpuspeed.awk /var/run/dmesg.boot`;
else
	cpuspeed='';
fi

if [ x$cpuspeed = x ] || [ $cpuspeed = 0 ]; then
	echo "unknown";

# XXX hack for minibed
elif [ $cpuspeed = "850" -a -x $BINDIR/chipset.awk ]; then
	if [ `$BINDIR/chipset.awk /var/run/dmesg.boot` = "GX" ]; then
		echo pcL440GX;
	else
		echo pc$cpuspeed;
	fi

else
	echo pc$cpuspeed;
fi
