/*
 * Automatically generated by jrpcgen 1.0.5 on 14-Feb-05 4:35:56 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class camera_config implements XdrAble {
    public String hostname;
    public int port;
    public float x;
    public float y;
    public float width;
    public float height;

    public camera_config() {
    }

    public camera_config(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeString(hostname);
        xdr.xdrEncodeInt(port);
        xdr.xdrEncodeFloat(x);
        xdr.xdrEncodeFloat(y);
        xdr.xdrEncodeFloat(width);
        xdr.xdrEncodeFloat(height);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        hostname = xdr.xdrDecodeString();
        port = xdr.xdrDecodeInt();
        x = xdr.xdrDecodeFloat();
        y = xdr.xdrDecodeFloat();
        width = xdr.xdrDecodeFloat();
        height = xdr.xdrDecodeFloat();
    }

}
// End of camera_config.java
