/*
 * Automatically generated by jrpcgen 1.0.5 on 14-Feb-05 4:35:56 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class contact_point implements XdrAble {
    public float x;
    public float y;

    public contact_point() {
    }

    public contact_point(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeFloat(x);
        xdr.xdrEncodeFloat(y);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        x = xdr.xdrDecodeFloat();
        y = xdr.xdrDecodeFloat();
    }

}
// End of contact_point.java
