/*
 * Automatically generated by jrpcgen 1.0.5 on 1/8/05 2:03 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class global_bound implements XdrAble {
    public float horizontal;
    public float vertical;

    public global_bound() {
    }

    public global_bound(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeFloat(horizontal);
        xdr.xdrEncodeFloat(vertical);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        horizontal = xdr.xdrDecodeFloat();
        vertical = xdr.xdrDecodeFloat();
    }

}
// End of global_bound.java
