/*
 * Automatically generated by jrpcgen 1.0.5 on 1/8/05 2:03 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

/**
 * A collection of constants used by the "mtp" ONC/RPC program.
 */
public interface mtp {
    public static final int FOO = 0x20049679;
    public static final int FIRST_DEMO_VERSION = 1;
    public static final int NULL_1 = 0;
    public static final int MTP_VERSION = 0x02;
}
// End of mtp.java
