/*
 * Automatically generated by jrpcgen 1.0.5 on 14-Feb-05 4:35:56 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class mtp_update_position implements XdrAble {
    public int robot_id;
    public robot_position position;
    public int status;
    public int command_id;

    public mtp_update_position() {
    }

    public mtp_update_position(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(robot_id);
        position.xdrEncode(xdr);
        xdr.xdrEncodeInt(status);
        xdr.xdrEncodeInt(command_id);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        robot_id = xdr.xdrDecodeInt();
        position = new robot_position(xdr);
        status = xdr.xdrDecodeInt();
        command_id = xdr.xdrDecodeInt();
    }

}
// End of mtp_update_position.java
