/*
 * Automatically generated by jrpcgen 1.0.5 on 14-Feb-05 4:35:56 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

/**
 * Enumeration (collection of constants).
 */
public interface mtp_wiggle_t {

    public static final int MTP_WIGGLE_START = 1;
    public static final int MTP_WIGGLE_180_R = 10;
    public static final int MTP_WIGGLE_180_R_L = 11;
    public static final int MTP_WIGGLE_360_R = 12;
    public static final int MTP_WIGGLE_360_R_L = 13;

}
// End of mtp_wiggle_t.java
