/*
 * Automatically generated by jrpcgen 1.0.5 on 14-Feb-05 4:35:56 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class mtp_config_rmc implements XdrAble {
    public robot_config [] robots;
    public box [] bounds;
    public obstacle_config [] obstacles;

    public mtp_config_rmc() {
    }

    public mtp_config_rmc(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = robots.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { robots[$idx].xdrEncode(xdr); } }
        { int $size = bounds.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { bounds[$idx].xdrEncode(xdr); } }
        { int $size = obstacles.length; xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { obstacles[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = xdr.xdrDecodeInt(); robots = new robot_config[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { robots[$idx] = new robot_config(xdr); } }
        { int $size = xdr.xdrDecodeInt(); bounds = new box[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { bounds[$idx] = new box(xdr); } }
        { int $size = xdr.xdrDecodeInt(); obstacles = new obstacle_config[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { obstacles[$idx] = new obstacle_config(xdr); } }
    }

}
// End of mtp_config_rmc.java
