/*
 * Automatically generated by jrpcgen 1.0.5 on 1/8/05 2:03 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class mtp_telemetry implements XdrAble {
    public int type;
    public mtp_garcia_telemetry garcia;

    public mtp_telemetry() {
    }

    public mtp_telemetry(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(type);
        switch ( type ) {
        case mtp_robot_type_t.MTP_ROBOT_GARCIA:
            garcia.xdrEncode(xdr);
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        type = xdr.xdrDecodeInt();
        switch ( type ) {
        case mtp_robot_type_t.MTP_ROBOT_GARCIA:
            garcia = new mtp_garcia_telemetry(xdr);
            break;
        }
    }

}
// End of mtp_telemetry.java
