/*
 * Automatically generated by jrpcgen 1.0.5 on 1/8/05 2:03 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

/**
 * Enumeration (collection of constants).
 */
public interface mtp_role_t {

    public static final int MTP_ROLE_VMC = 1;
    public static final int MTP_ROLE_EMC = 2;
    public static final int MTP_ROLE_RMC = 3;
    public static final int MTP_ROLE_EMULAB = 4;
    public static final int MTP_ROLE_ROBOT = 5;
    public static final int MTP_ROLE_MAX = 5+1;

}
// End of mtp_role_t.java
