/*
 * Automatically generated by jrpcgen 1.0.5 on 1/8/05 2:03 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class mtp_control implements XdrAble {
    public int id;
    public int code;
    public String msg;

    public mtp_control() {
    }

    public mtp_control(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(id);
        xdr.xdrEncodeInt(code);
        xdr.xdrEncodeString(msg);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        id = xdr.xdrDecodeInt();
        code = xdr.xdrDecodeInt();
        msg = xdr.xdrDecodeString();
    }

}
// End of mtp_control.java
