/*
 * Automatically generated by jrpcgen 1.0.5 on 1/8/05 2:03 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class mtp_request_position implements XdrAble {
    public int robot_id;

    public mtp_request_position() {
    }

    public mtp_request_position(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(robot_id);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        robot_id = xdr.xdrDecodeInt();
    }

}
// End of mtp_request_position.java
