/*
 * Automatically generated by jrpcgen 1.0.5 on 14-Feb-05 4:35:56 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class mtp_contact_report implements XdrAble {
    public int count;
    public contact_point [] points;

    public mtp_contact_report() {
    }

    public mtp_contact_report(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(count);
        { int $size = 8; for ( int $idx = 0; $idx < $size; ++$idx ) { points[$idx].xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        count = xdr.xdrDecodeInt();
        { int $size = 8; points = new contact_point[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { points[$idx] = new contact_point(xdr); } }
    }

}
// End of mtp_contact_report.java
