/*
 * Automatically generated by jrpcgen 1.0.5 on 14-Feb-05 4:35:56 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class obstacle_config implements XdrAble {
    public int id;
    public float xmin;
    public float ymin;
    public float zmin;
    public float xmax;
    public float ymax;
    public float zmax;

    public obstacle_config() {
    }

    public obstacle_config(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(id);
        xdr.xdrEncodeFloat(xmin);
        xdr.xdrEncodeFloat(ymin);
        xdr.xdrEncodeFloat(zmin);
        xdr.xdrEncodeFloat(xmax);
        xdr.xdrEncodeFloat(ymax);
        xdr.xdrEncodeFloat(zmax);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        id = xdr.xdrDecodeInt();
        xmin = xdr.xdrDecodeFloat();
        ymin = xdr.xdrDecodeFloat();
        zmin = xdr.xdrDecodeFloat();
        xmax = xdr.xdrDecodeFloat();
        ymax = xdr.xdrDecodeFloat();
        zmax = xdr.xdrDecodeFloat();
    }

}
// End of obstacle_config.java
