/*
 * Automatically generated by jrpcgen 1.0.5 on 1/8/05 2:03 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
package net.emulab;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class robot_position implements XdrAble {
    public float x;
    public float y;
    public float theta;
    public double timestamp;

    public robot_position() {
    }

    public robot_position(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeFloat(x);
        xdr.xdrEncodeFloat(y);
        xdr.xdrEncodeFloat(theta);
        xdr.xdrEncodeDouble(timestamp);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        x = xdr.xdrDecodeFloat();
        y = xdr.xdrDecodeFloat();
        theta = xdr.xdrDecodeFloat();
        timestamp = xdr.xdrDecodeDouble();
    }

}
// End of robot_position.java
