#! /bin/sh

extension=''
for ext in .lzma .bz2 .gz ''; do
	if [ -f initramfs$ext ]; then
		extension="$ext"
		break
	fi
done

if [ -z "$extension" ] && ! [ -f initramfs ]; then
	echo "No initramfs present; aborting..." 1>&2
	exit 1
fi

rm -rf extracted_initramfs
mkdir -p extracted_initramfs
cd extracted_initramfs

case $ext in
	.lzma) compression=lzma ;;
	.bz2) compression=bzip2 ;;
	.gz) compression=gzip ;;
	*) compression=none ;;
esac

(
if [ $compression = none ]; then
	cpio -idu
else
	$compression -dc | cpio -idu
fi
) < ../initramfs$extension
