#!/bin/sh

. /etc/emulab/paths.sh

trap 'exit 0' 15

echo $* >> /tmp/dh

cnet=`$BINDIR/control_interface`
if [ -z "$cnet" ]; then
	echo "WARNING: unknown control net interface, DHCP on all..."
	/sbin/dhclient
else
	/sbin/dhclient $cnet
fi
exit 0
