import java.awt.*;
import java.util.*;

public class WorkArea {
    private Vector thingees;
    private Vector linkThingees;
    private Vector iFaceThingees;

    public WorkArea() {
	super();
	thingees = new Vector();
	linkThingees = new Vector();
	iFaceThingees = new Vector();
	//Thingee foo = new Thingee( "Some Node" );
	//foo.move( 100, 100 );
	//thingees.addElement( foo  );
    }


    public String toNS() {
	Dictionary lanConnections = new Hashtable();
	String r = "";
	
	r += "#generated by Netbuild\n";
	r += "set ns [new Simulator]\n";
	r += "source tb_compat.tcl\n\n";
	
	Enumeration e;

	String s;
	String n;

	Dictionary names;

	boolean good = false;
	while (!good) {
	    names = new Hashtable();
	    good = true;
	    e = thingees.elements();
	    while (good && e.hasMoreElements()) {
		Thingee t = (Thingee)e.nextElement();
		if (t.getName().compareTo("") == 0) {
		    good = false;
		    // t += "# WARNING! Changed name for 
		    t.setName( t.genName( "gen_name_" ) );
		    Netbuild.setStatus("!Duplicate and/or blank names were changed.");
		} else if (names.get(t.getName()) != null) {
		    good = false;
		    t.setName( t.genName( t.getName() ) );
		    Netbuild.redrawAll();
		    Netbuild.setStatus("!Duplicate and/or blank names were changed.");
		} else {
		    names.put(t.getName(), t );
		}
	    }
	}


	e = thingees.elements();
	while ( e.hasMoreElements()) {
	    Thingee t = (Thingee)e.nextElement();
	    if (t instanceof NodeThingee) {
		n = t.getName();
		r += "set " + n + " [$ns node]\n";
		s = t.getProperty( "osid", "" );
		if (0 != s.compareTo("<auto>") &&
		    0 != s.compareTo("")) {
		    r += "tb-set-node-os $" + n + " " + s + "\n";
		}
		s = t.getProperty( "hardware", "" );
		if (0 != s.compareTo("<auto>") &&
		    0 != s.compareTo("")) {
		    r += "tb-set-hardware $" + n + " " + s + "\n";
		}
	    }
	}	

	r += "\n";

	e = linkThingees.elements();
	while (e.hasMoreElements()) {
	    Thingee t1 = (Thingee)e.nextElement();
	    if (!(t1 instanceof LanLinkThingee)) {
		// it's a node link
		LinkThingee t = (LinkThingee)t1;
		n = t.getName();
		String a = t.getA().getName();
		String b = t.getB().getName();
		String bandwidth = t.getProperty( "bandwidth", "100" ) + "Mb";
		String latency = t.getProperty( "latency", "0" ) + "ms";
		r += "set " + n + " [$ns duplex-link $" + a + " $" + b +
		    " " + bandwidth + " " + latency + " DropTail]\n";
		try {
		    Float loss = new Float(t.getProperty( "loss", "0.0" ));
		    float l = loss.floatValue();
		    if (l > 1.0f) { l = 1.0f; }
		    if (l > 0.0f) {
			r += "tb-set-link-loss $" + n + " " + String.valueOf(l) + "\n" ; // XXX
		    }
		} catch (Exception ex) {} 
	    } else {
		// it's a lan link
		LinkThingee t = (LanLinkThingee)t1;
		Thingee node,lan;
		if (t.getA() instanceof LanThingee) {
		    lan = t.getA();
		    node = t.getB();
		} else {
		    lan = t.getB();
		    node = t.getA();
		}
		Vector v = (Vector)lanConnections.get( lan.getName() );
		if (v == null) {
		    v = new Vector();
		    lanConnections.put( lan.getName(), v );
		}
		v.addElement( node );
		//tb-set-node-lan-params $node0 $lan0 40ms 20Mb 0.05
	    }
	}
	
	r += "\n";

	e = iFaceThingees.elements();

	while (e.hasMoreElements()) {
	    Thingee t1 = (Thingee)e.nextElement();
	    if (t1 instanceof IFaceThingee) {
		IFaceThingee t = (IFaceThingee)t1;
		LinkThingee lt = null;
		NodeThingee nt = null; 
		if ( t.getA() instanceof LinkThingee ) {
		    lt = (LinkThingee)t.getA();
		    nt = (NodeThingee)t.getB();
		} else if (t.getB() instanceof LinkThingee ) {
		    lt = (LinkThingee)t.getB();
		    nt = (NodeThingee)t.getA();
		}

		if (lt != null && !(lt instanceof LanLinkThingee)) {
		    s = t.getProperty( "ip", "<auto>" );
		    if (0 != s.compareTo("<auto>") &&
			0 != s.compareTo("")) {
			r += "tb-set-ip-link $" + nt.getName() + 
			    " $" + lt.getName() + " " + s + "\n";
		    }
		}		    
	    }
	}

	r += "\n";

	e = thingees.elements();
	while ( e.hasMoreElements()) {
	    Thingee t = (Thingee)e.nextElement();
	    if (t instanceof LanThingee) {
		Vector v = (Vector)lanConnections.get( t.getName() );
		if (v != null) {
		    r += "set " + t.getName() + " [$ns make-lan \"";
		    Enumeration ce = v.elements();
		    while (ce.hasMoreElements()) {
			Thingee cet = (Thingee)ce.nextElement();
			r += "$" + cet.getName() + " ";
		    }
		    String bandwidth = t.getProperty( "bandwidth", "100" ) 
			+ "Mb";
		    String latency = t.getProperty( "latency", "0" ) + "ms";
		    r += "\" " + bandwidth + " " + latency + "]\n";

		    try {
			Float loss = new Float(t.getProperty( "loss", "0.0" ));
			float l = loss.floatValue();
			if (l > 1.0f) { l = 1.0f; }
			if (l > 0.0f) {
			    r += "tb-set-lan-loss $" + t.getName() + " " + String.valueOf(l) + "\n";
			}
		    } catch (Exception ex) {} 
		}
	    }
	}

	r += "\n";

	e = linkThingees.elements();
	while (e.hasMoreElements()) {
	    Thingee t1 = (Thingee)e.nextElement();
	    if (t1 instanceof LanLinkThingee) {
		// it's a lan link
		LanLinkThingee t = (LanLinkThingee)t1;
		Thingee node,lan;
		if (t.getA() instanceof LanThingee) {
		    lan = t.getA();
		    node = t.getB();
		} else {
		    lan = t.getB();
		    node = t.getA();
		}
		//tb-set-node-lan-params $node0 $lan0 40ms 20Mb 0.05
		String bandwidth = t.getProperty( "bandwidth", "100" ) + "Mb";
		String latency = t.getProperty( "latency", "0" ) + "ms";
		float l = 0.0f;
		try {
		    Float loss = new Float(t.getProperty( "loss", "0.0" ));
		    l = loss.floatValue();
		    if (l > 1.0f) { l = 1.0f; }
		} catch (Exception ex) {} 
		r += "tb-set-node-lan-params $" + node.getName() + " $" +
		    lan.getName() + " " + latency + " " + bandwidth + " " + String.valueOf(l) + "\n";
	    }
	}

	r += "\n";

	e = iFaceThingees.elements();

	while (e.hasMoreElements()) {
	    Thingee t1 = (Thingee)e.nextElement();
	    if (t1 instanceof IFaceThingee) {
		IFaceThingee t = (IFaceThingee)t1;
		LinkThingee lt = null;
		NodeThingee nt = null; 
		if ( t.getA() instanceof LinkThingee ) {
		    lt = (LinkThingee)t.getA();
		    nt = (NodeThingee)t.getB();
		} else if (t.getB() instanceof LinkThingee ) {
		    lt = (LinkThingee)t.getB();
		    nt = (NodeThingee)t.getA();
		}

		if (lt != null && (lt instanceof LanLinkThingee)) {
		    LanLinkThingee llt = (LanLinkThingee)lt;
		    LanThingee lant;
		    if (llt.getA() instanceof LanThingee) {
			lant = (LanThingee)llt.getA();
		    } else {
			lant = (LanThingee)llt.getB();
		    }	       
		    s = t.getProperty( "ip", "<auto>" );
		    if (0 != s.compareTo("<auto>") &&
			0 != s.compareTo("")) {
			r += "tb-set-ip-lan $" + nt.getName() + 
			    " $" + lant.getName() + " " + s + "\n";
		    }
		}		    
	    }
	}

	r += "\n$ns rtproto Static\n";
	r += "$ns run\n";
	r += "#netbuild-generated ns file ends.\n";
	
	return r;
	
	// #generated by Netbuild
	// set ns [new Simulator]
	// source tb_compat.tcl
	// 
	// set NodeA [$ns node]
	// set NodeB [$ns node]
	//
	// tb-set-node-os $NodeA FBSD-STD
	//
	// set LinkA [$ns duplex-link $NodeA $NodeB 100Mb 50ms DropTail]
	// set LinkB [$ns duplex-link $NodeA $NodeB 100Mb .1ms DropTail]
	// tb-set-link-loss $LinkA 0.05
	// tb-set-ip-link $NodeB $linkA 192.168.42.42
	//
	// set lan0 [$ns make-lan "$node0 $node1" 100Mb .1ms]
	// tb-set-lan-loss $Lan1 0.3
	//
	// tb-set-ip-lan $NodeB $lan1 123.4.5.6
	// tb-set-node-lan-delay     $lan0 $node0 40ms
	// tb-set-node-lan-bandwidth $lan0 $node0 20Mb
	// tb-set-node-lan-loss      $lan0 $node0 0.2
        //
	// $ns run
	
    }

    public void copySelected() {
	Dictionary map = new Hashtable();
	Vector newIFaces = new Vector();
	Enumeration e = Thingee.selectedElements();
	
	// copy selected nodes
	while (e.hasMoreElements()) {
	    Thingee t = (Thingee)e.nextElement();
	    
	    if (t instanceof NodeThingee) {
		NodeThingee nt = new NodeThingee( Thingee.genName( t.getName() ));
		nt.move( t.getX() + 16, t.getY() + 16 );
		nt.copyProps( t );
		add( nt );
		map.put( t, nt );
	    } else if (t instanceof LanThingee) {
		LanThingee nt = new LanThingee( Thingee.genName( t.getName() ));
		nt.move( t.getX() + 16, t.getY() + 16 );
		nt.copyProps( t );
		add( nt );
		map.put( t, nt );
	    }
	}	

	e = Thingee.selectedElements();
	
	// now copy selected links
	while (e.hasMoreElements()) {
	    Thingee t = (Thingee)e.nextElement();
	    
	    if ((t instanceof LinkThingee) && !(t instanceof LanLinkThingee))  {
		LinkThingee lt = (LinkThingee)t;
		Thingee a = (Thingee)map.get( lt.getA() );
		Thingee b = (Thingee)map.get( lt.getB() );
		String name = lt.getName();
		if (0 != name.compareTo("")) {
		    name = Thingee.genName( name );
		}
		if (a != null && b != null) {
		    LinkThingee nt = new LinkThingee( name, a, b );
		    nt.copyProps( t );
		    add( nt );
		    map.put( t, nt );

		    IFaceThingee i  = new IFaceThingee( "", a, nt );
		    IFaceThingee i2 = new IFaceThingee( "", b, nt );

		    add(i);
		    add(i2);
		    newIFaces.addElement( i  );
		    newIFaces.addElement( i2 );
		}
	    } else if (t instanceof LanLinkThingee) {
		LanLinkThingee lt = (LanLinkThingee)t;
		Thingee a = (Thingee)map.get( lt.getA() );
		Thingee b = (Thingee)map.get( lt.getB() );
		if (a != null && b != null) {
		    LanLinkThingee nt = new LanLinkThingee( "", a, b );
		    nt.copyProps( t );
		    add( nt );
		    map.put( t, nt );

		    Thingee node;
		    if (a instanceof NodeThingee) { node = a; } else { node = b; }
		    IFaceThingee i  = new IFaceThingee( "", node, nt );
		    add(i);
		    newIFaces.addElement( i  );
		}
	    }
	}	


	Thingee.deselectAll();
	
	e = map.elements();
	while (e.hasMoreElements()) {
	    Thingee t = (Thingee)e.nextElement();
	    t.select();
	}

	e = newIFaces.elements();
	while (e.hasMoreElements()) {
	    Thingee t = (Thingee)e.nextElement();
	    t.select();
	}

    }


    private void selectOneInRectangle( Rectangle r, Thingee t, boolean xor ) {
	int xDiff = t.getX() - r.x;
	int yDiff = t.getY() - r.y;
	if (xDiff > 0 && xDiff < r.width &&
	    yDiff > 0 && yDiff < r.height) {
	    if (!xor || !t.isSelected()) {
		t.select();
	    } else {
		t.deselect();
	    }
	}
    }




    public void selectRectangle( Rectangle r, boolean xor ) {
	Enumeration linkThingeeEnum = linkThingees.elements();

	while ( linkThingeeEnum.hasMoreElements()) {
	    Thingee t = (Thingee)linkThingeeEnum.nextElement();
	    selectOneInRectangle( r, t, xor );
	}

	Enumeration thingeeEnum = thingees.elements();

	while ( thingeeEnum.hasMoreElements()) {
	    Thingee t = (Thingee)thingeeEnum.nextElement();
	    selectOneInRectangle( r, t, xor );
	}

	Enumeration iFaceThingeeEnum = iFaceThingees.elements();

	while ( iFaceThingeeEnum.hasMoreElements()) {
	    Thingee t = (Thingee)iFaceThingeeEnum.nextElement();
	    selectOneInRectangle( r, t, xor );
        }
    }

    public int getThingeeCount() {
	return linkThingees.size() + thingees.size() + iFaceThingees.size();
    }

    public void paint( Graphics g ) {
	Enumeration linkThingeeEnum = linkThingees.elements();

	while ( linkThingeeEnum.hasMoreElements()) {
	    Thingee t = (Thingee)linkThingeeEnum.nextElement();
	    t.draw( g );
	}

	Enumeration thingeeEnum = thingees.elements();

	while ( thingeeEnum.hasMoreElements()) {
	    Thingee t = (Thingee)thingeeEnum.nextElement();
	    t.draw( g );
	}

	Enumeration iFaceThingeeEnum = iFaceThingees.elements();

	while ( iFaceThingeeEnum.hasMoreElements()) {
	    Thingee t = (Thingee)iFaceThingeeEnum.nextElement();
	    t.draw( g );
	}
    }

    public Thingee clicked( int x, int y ) {
      	Enumeration thingeeEnum;

	Thingee got = null;

      	thingeeEnum = linkThingees.elements();

	while ( thingeeEnum.hasMoreElements()) {
	    Thingee t = (Thingee)thingeeEnum.nextElement();
	    if (t.clicked(x, y)) { got = t; }
	}

      	thingeeEnum = thingees.elements();

	while ( thingeeEnum.hasMoreElements()) {
	    Thingee t = (Thingee)thingeeEnum.nextElement();
	    if (t.clicked(x, y)) { got = t; }
	}

	thingeeEnum = iFaceThingees.elements();

	while ( thingeeEnum.hasMoreElements()) {
	    Thingee t = (Thingee)thingeeEnum.nextElement();
	    if (t.clicked(x, y)) { got = t; }
	}

	return got;
    }

    public void remove( Thingee t ) {
	if (t instanceof IFaceThingee) {
	    iFaceThingees.removeElement( t );
	} else if (t instanceof LinkThingee) {
	    boolean done = false;
	    while (!done) {
		done = true;
		Enumeration e = iFaceThingees.elements();
		while (e.hasMoreElements() && done) {
		    IFaceThingee i = (IFaceThingee)e.nextElement();
		    if (i.isConnectedTo(t)) {
			remove( i );
			done = false;
		    }
		}
	    }
	    linkThingees.removeElement( t );
	} else {
	    boolean done = false; // stupid hack.
	    while (!done) {
		done = true;
		Enumeration thingeeEnum = linkThingees.elements();
		while ( thingeeEnum.hasMoreElements() && done) {
		    LinkThingee u = (LinkThingee)thingeeEnum.nextElement();
		    if (u.isConnectedTo(t)) { 
			remove( u );
			done = false;
		    }
		}
	    }
	    thingees.removeElement( t );
	}
    }

    public void add( Thingee t ) {
	if (t instanceof LinkThingee) {
	    linkThingees.addElement( t );
	} else if (t instanceof IFaceThingee) {
	    iFaceThingees.addElement( t );
	} else {
	    thingees.addElement( t );
	}
    }
};
