#!/usr/bin/perl
package TestBed::XMLRPC::Client::Emulab;
use SemiModern::Perl;
use Mouse;
use Data::Dumper;

extends 'TestBed::XMLRPC::Client';

=head1 NAME

TestBed::XMLRPC::Client::Emulab

=over 4

=item C<news()>

returns the emulab news

=back

=cut

#autoloaded/autogenerated/method_missings/etc news

1;
