#!/usr/bin/perl
use SemiModern::Perl;

package TestBed::XMLRPC::Client::Emulab;
use Mouse;
use Data::Dumper;

extends 'TestBed::XMLRPC::Client';

#autoloaded/autogenerated/method_missings/etc news

1;
