#!/usr/bin/perl
package TestBed::XMLRPC::Client::Node;
use SemiModern::Perl;
use Mouse;
use Data::Dumper;

extends 'TestBed::XMLRPC::Client';

#autoloaded/autogenerated/method_missings/etc available getlist typeinfo

=head1 NAME

TestBed::XMLRPC::Client::Node

=over 4

=item C<available>

returns a list of available nodes

=item C<getlist>

returns a list of available nodes

=back

=cut

sub filter_hash {
  my ($hash, $proc) = @_;
  my %new_hash;
  while (my ($k, $v) = each %$hash) {
    if ( $proc->($k, $v) ) {
      $new_hash{$k} = $v;
    }
  }
  \%new_hash;
}

sub _free {
  my ($k, $v) = @_;
  $v->{'free'} == 1;
}

sub get_free {
  filter_hash(
    shift->augment_func( 'getlist', @_ ),
    \&_free);
}

sub get_free_names {
  keys %{shift->get_free(@_)};
}
1;
