#!/usr/bin/perl
package TestBed::XMLRPC::Client::Node::InsufficientNodes;
use Mouse;

package TestBed::XMLRPC::Client::Node;
use SemiModern::Perl;
use Mouse;
use Data::Dumper;

extends 'TestBed::XMLRPC::Client';

#autoloaded/autogenerated/method_missings/etc available getlist typeinfo

sub filter_hash {
  my ($hash, $proc) = @_;
  my %new_hash;
  while (my ($k, $v) = each %$hash) {
    if ( $proc->($k, $v) ) {
      $new_hash{$k} = $v;
    }
  }
  \%new_hash;
}

sub _free {
  my ($k, $v) = @_;
  $v->{'free'} == 1;
}

sub get_free {
  filter_hash(
    shift->augment_func( 'getlist', @_ ),
    \&_free);
}

sub get_free_names {
  my $x = shift;
  sayd(keys %{$x->get_free(@_)});
  keys %{$x->get_free(@_)};
}

sub get_free_node_names {
  my $node = shift;
  my $qty = shift;
  my @names = $node->get_free_names(@_);
  if (scalar @names < $qty ) { die TestBed::XMLRPC::Client::Node::InsufficientNodes->new; }
  return @names;
}

=head1 NAME

TestBed::XMLRPC::Client::Node

=over 4

=item C<available>

returns a list of available nodes

=item C<getlist>

returns a list of available nodes

=item C<filter_hash($hash, $proc)>

returns a new has containing key,value pairs that $proce returned true for

=item C<get_free()>

given a list of nodeshashes return nodehashes for nodes that are free

=item C<get_free_names( param => value, ...)>

returns a list of free node names that meet criteria of params => values

=item C<get_free_node_names($qrt, )>

returns a list of at least $qty free node names that meet criteria of params => values

=back

=cut

1;
