# New ports collection makefile for: ulsshxmlrpcpp
# Date created:         24 August, 2004
# Whom:                 ricci@cs.utah.edu

PORTNAME=	ulsshxmlrpcpp
PORTVERSION=	0.1.2
CATEGORIES=	misc
MASTER_SITES=	http://www.emulab.net/distributions/

MAINTAINER=	ricci@cs.utah.edu
COMMENT=	"C++ Libraries for performing XML-RPC through ssh"

HAS_CONFIGURE=	yes
USE_GMAKE=	yes
INSTALLS_SHLIB=	yes

.include <bsd.port.mk>
